Fix: Navigating using arrows in ColumnView no longer crashes the app
files-community/Files pull request #10421
Opened 2022-11-07 13:19 UTC by QuaintMako

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #10109 

**What has been done**
- Programmatically handling the change of focus between the columns.
- Minor refactoring.

**Validation**
How did you test these changes?
- [X] Built and ran the app

**Screenshots**

![CrashTabFixDraft](https://user-images.githubusercontent.com/110472580/200320459-6d8e9a1b-a12a-4182-b783-10b9a0a5767c.gif)

2022-11-07 13:24 UTC, QuaintMako commented
The work for this PR is not complete yet, but I have an hard time finishing it.

There are several limitations currently preventing it to be considered fully functional:

1. When moving from the left or right, it will always refocus the first element of the `FileList`. When returning to the preview folder, it should focus the parent folder.
2. When moving the focus, the item is not "fully focused", as you can see on the gif. The user needs to press the down arrow to fully select the item.

If anyone fancy giving it a shot, I'll gladly take the help! In any case, I'm still looking into it.

2022-11-07 15:10 UTC, QuaintMako commented
The work for this PR is almost done, but I cannot find a cleaner way to refresh the selection when backing up to the previous folder between line.222 and line.226 in `ColumnViewBrowser.xaml.cs`. If anyone has an idea, I'll gladly take it.

2022-11-08 17:29 UTC, QuaintMako commented
> The work for this PR is almost done, but I cannot find a cleaner way to refresh the selection when backing up to the previous folder between line.222 and line.226 in `ColumnViewBrowser.xaml.cs`. If anyone has an idea, I'll gladly take it.

Cannot find a cleaner way to solve this problem, so I'm opening it for review.

2022-11-10 20:08 UTC, ferrariofilippo requested changes
There are some problems with the code style and lines 402 -> 410 (`src.Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs`), otherwise it is fine.

2022-11-10 20:08 UTC, ferrariofilippo commented on src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
> +					return;
I am not sure about two things:
- Is it worth double-checking `currentBladeIndex`? (Its value is checked both here and in `MoveFocusToPreviousBlade`)
- I think `e.Handled` should be set to true anyway, as you did for `VirtualKey.Right`

2022-11-10 20:08 UTC, ferrariofilippo commented on src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
> +				return;
Can you change `==` to `is`? We have just changed this throughout the whole code base (#10326)

2022-11-10 20:08 UTC, ferrariofilippo commented on src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
> +			if (activeBladeColumnViewBase != null)
Same as above

2022-11-10 20:08 UTC, ferrariofilippo commented on src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
> +			if (activeBladeFrame == null)
Same as above

2022-11-10 20:08 UTC, ferrariofilippo commented on src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
> +			if (activeBladePage == null)
Same as above

2022-11-10 20:32 UTC, ferrariofilippo commented
I may have found a bug but I'm not sure if it's related to this PR and the way we focus a blade.
Sometimes, while navigating between columns, it happens that the focus bounces between the last two blades.
I post here a video to show what happens.

https://user-images.githubusercontent.com/102259289/201199645-6e1243e5-e200-4a0f-b79c-511233a5e7e7.mp4

2022-11-11 17:10 UTC, QuaintMako commented
> I may have found a bug but I'm not sure if it's related to this PR and the way we focus a blade. Sometimes, while navigating between columns, it happens that the focus bounces between the last two blades. I post here a video to show what happens.

I'm going to investigate this. It is probably linked to this PR, since beforehand we would not even move between the blades.

2022-11-11 17:25 UTC, QuaintMako commented
After messing around a bit with the feature, I think it's not linked to the PR at all. Moving up and down with the arrows messes the display as well. I did not touch those. I propose to open another issue about this<
Thoughts @ferrariofilippo ?

2022-11-12 13:30 UTC, ferrariofilippo commented
> I propose to open another issue about this

I'll do so.

2022-11-12 13:31 UTC, ferrariofilippo approved these changes
LGTM

2022-11-14 18:25 UTC, yaichenbaum approved these changes
LGTM

2022-11-14 18:25 UTC, merged