Improves Files.App.Storage
files-community/Files pull request #10834
Opened 2022-12-23 20:14 UTC by cinqmilleans

**Resolved / Related Issues**
Clean Storage code.

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

2022-12-26 16:55 UTC, QuaintMako approved these changes
LGTM. I haven't seen any problem.

`src/Files.App.Storage/FtpStorage/FtpStorageFolder.cs` and `src/Files.App.Storage/WindowsStorage/WindowsStorageFolder.cs` are alike on some spaces, but I do not think it'd be wise to try to fuse them.

2022-12-27 00:17 UTC, d2dyno1 requested changes

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpFileSystemService.cs
> -		{
I'd keep it as is.

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpFileSystemService.cs
> +			using AsyncFtpClient client = path.GetFtpClient();
`using` statement here will dispose the client after the method exits. Remove it from here

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpHelpers.cs
> +		public static string GetFtpPath(this string path)
Don't make GetFtpPath an extension method on string!!!!

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.Shared/Helpers/PathHelpers.cs
> +		public static string GetParentDir(this string path)
Nooo!!!

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.Shared/Helpers/PathHelpers.cs
> +		public static string Combine(this string folder, string name)
"Nooo!!!" here too

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpFileSystemService.cs
> +			using AsyncFtpClient client = path.GetFtpClient();
Besides, you could refactor the method in FtpStorable.GetFtpClientAsync() - to use a `string path` parameter, and remove this method

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpStorable.cs
> +			=> Task.FromResult<ILocatableFolder?>(null);
Revert this change please :)

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpStorable.cs
> +		public string Id => string.Empty;
fyi, I wouldn't do anything to this for now, as `Id` will be implemented [_**here**_](https://github.com/files-community/Files/pull/10477/commits/fcc9db77ba895cbe503b569d521bb73ab8a753d6). (And in other places as well)

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpStorable.cs
> +		protected async Task<AsyncFtpClient> GetFtpClient(CancellationToken cancellationToken = default)
Rename to `GetFtpClientAsync`

2022-12-27 00:17 UTC, d2dyno1 commented on src/Files.App.Storage/FtpStorage/FtpStorageFile.cs
> +		public FtpStorageFile(string path, string name) : base(path, name) {}
Revert this change :) (And in other places too)

2022-12-27 09:56 UTC, cinqmilleans commented
@d2dyno1 @yaira2 @QuaintMako This pr has a lot of cancellation requests and conflicts with #10477. I am closing it because it is no longer needed.

2022-12-27 09:56 UTC, closed without merging