Fix: Remove unnecessary async state machine generation
files-community/Files pull request #10853
Opened 2022-12-27 15:39 UTC by hecksmosis

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #9871 

**Validation**
How did you test these changes?
- [*] Built and ran the app

**Screenshots (optional)**
Add screenshots here.

2022-12-27 15:49 UTC, hez2010 requested changes
Otherwise LGTM.

2022-12-27 15:49 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
> +            return null;
They are not equivalent, instead using

```suggestion
            return Task.FromResult<BaseStorageFile>(null).AsAsyncOperation();
```

2022-12-27 15:49 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
> +			return null;
They are not equivalent, instead using

```suggestion
			return Task.FromResult<BaseStorageFolder>(null).AsAsyncOperation();
```

2022-12-27 15:49 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
> +				return null;
They are not equivalent, instead using

```suggestion
				return Task.FromResult<BaseStorageFolder>(null).AsAsyncOperation();
```

2022-12-27 16:17 UTC, hecksmosis commented
That should be it then.

2022-12-27 21:40 UTC, jiejasonliu commented on src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
> +		public static IAsyncOperation<BaseStorageFile>? FromPathAsync(string path)
with those changes, the nullable return doesn't make sense anymore right?

2022-12-28 01:16 UTC, jentur-zabbeJ-8basdy requested changes

2022-12-28 01:16 UTC, jentur-zabbeJ-8basdy commented on src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
> -				return new FileStream(hFile, accessMode == FileAccessMode.ReadWrite ? FileAccess.ReadWrite : FileAccess.Read).AsRandomAccessStream();
![Uploading FF4BC03A-09F1-4A22-ABCB-1D82B758D1F2.png…]()

2022-12-28 21:47 UTC, hecksmosis commented
@hez2010 Is everything ok now?

2022-12-29 01:15 UTC, hez2010 approved these changes
Can you also update the nullable type annotations?
Otherwise LGTM.

2022-12-29 01:15 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
>  		public static IAsyncOperation<BaseStorageFile> FromPathAsync(string path)
Nullable: `IAsyncOperation<BaseStorageFile?>`

2022-12-29 01:15 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/ZipStorageFile.cs
>  		public static IAsyncOperation<BaseStorageFile> FromPathAsync(string path)
Nullable: `IAsyncOperation<BaseStorageFile?>`

2022-12-29 01:15 UTC, hez2010 commented on src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
>  		public static IAsyncOperation<BaseStorageFolder> FromPathAsync(string path)
Nullable: `IAsyncOperation<BaseStorageFolder?>`

2022-12-29 04:17 UTC, yaira2 approved these changes
LGTM

2022-12-29 04:17 UTC, merged