Code Quality: Simplify ColorPicker control with `ColorPickerButton`
files-community/Files pull request #11724
Opened 2023-03-15 01:44 UTC by Poker-sang

**Details**
We can use new `ColorPickerButton` control to simplify code. It has better appearance and easy to maintain the code.

But both `ColorPicker` and `ColorPickerButton` under namespace `CommunityToolkit.WinUI.UI.Controls` have a XAML binding failure problem. I cannot help it and have to wait for _CommunityToolkit_ to fix.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots**
Old control:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/62325494/225182701-36e86bad-915e-4fba-b49f-91434a5be322.png">

New one:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/62325494/225182449-4f635181-75f7-4173-b6ff-e35cdffcb9da.png">

XAML Binding failure (Unable to fix now):
Error: Converter failed to convert value of type 'null' to type 'Color'; BindingExpression: Path='Color' DataItem='CommunityToolkit.WinUI.UI.Controls.ColorPicker'; target element is 'Microsoft.UI.Xaml.Controls.GridView' (Name='null'); target property is 'SelectedValue' (type 'Object').

2023-03-15 02:40 UTC, yaira2 commented
Thank you for the PR, I wasn't aware of this control. (In the future, it's recommended to open an issue to discuss a change before working on it).

Overall this looks good but there are two styling issues we should fix before merging
1. The button height should be a little taller to match the current control.
2. The arrow is too large, it should look the same as the current control.

2023-03-15 08:09 UTC, ferrariofilippo requested changes
You changed only one of the two color pickers in `TagsPage`, you can find the other one @ line 82.
~Adding a default value to `ListedTagViewModel.newColor` would prevent *XAML Exceptions* in TagsPage~

2023-03-15 08:09 UTC, ferrariofilippo commented on src/Files.App/Views/Settings/AppearancePage.xaml
>  				<local:SettingsBlockControl.ExpandableContent>
Is there any way to keep `IsColorSpectrumVisible="False"`?

2023-03-15 10:42 UTC, Poker-sang commented
> You changed only one of the two color pickers in `TagsPage`, you can find the other one @ line 82. Adding a default value to `ListedTagViewModel.newColor` would prevent _XAML Exceptions_ in TagsPage

@ferrariofilippo Sorry, can you provide more information? I had tried but failed, I thought it is bug from CommunityToolkit.

2023-03-15 11:08 UTC, Poker-sang commented
> Thank you for the PR, I wasn't aware this control existed. (In the future, it's recommended to open an issue to discuss a change before working on it).
> 
> Overall this looks good but there are two styling issues we should fix before merging
> 
> 1. The button height should be a little taller to match the current control.
> 2. The arrow is too large, it should look the same as the current control.

@yaira2 I'm sorry. And because CommunityToolkit.WinUI.Controls is based on WinUI2 (or UWP? I'm not sure), so the appearance is not fluent design.
So I thought we shall use `Microsoft.UI.Xaml.Controls.ColorPicker`, do you think so?

2023-03-15 11:18 UTC, ferrariofilippo commented
> @ferrariofilippo Sorry, can you provide more information? I had tried but failed, I thought it is bug from CommunityToolkit.

My bad, I got the exception with a little delay in debug mode and I thought it was fixed

2023-03-15 11:26 UTC, Poker-sang commented
> You changed only one of the two color pickers in `TagsPage`, you can find the other one @ line 82. 

Thanks for mentioning. I would fix it after deciding which ColorPicker to use.

2023-03-15 16:46 UTC, Poker-sang commented
It looks like we cannot avoid the Binding failure unless using `Microsoft.UI.Xaml.Controls.ColorPicker` instead. Do you think we should do this? @yaira2

2023-03-16 00:02 UTC, yaira2 commented
I went with the toolkit control because it had a nicer UX.

2023-03-16 00:10 UTC, Poker-sang commented
emm OK. But we have to wait for toolkit fix the bug.

2023-03-16 00:24 UTC, closed without merging

2023-03-16 00:50 UTC, yaira2 commented
Is there an issue on the Toolkit repo?

2023-04-05 14:10 UTC, Poker-sang commented
@yair100 Which control causes the bug? Is there a relevant issue or details

2023-04-05 15:10 UTC, yaira2 commented
It seems to be from the ColorPickerButton, changing the theme from one of the built-in options should properly apply the theme but it seems to only work if you choose a color from the color picker flyout.

2023-04-05 15:40 UTC, yaira2 commented
> I am not sure if ColorPicker in ToolKit has the same bug. I haven't written for so long that I've forgotten.

ColorPicker (from the Toolkit) doesn't have this issue.

2023-04-05 15:46 UTC, Poker-sang commented
Exactly. It is a bug appears in ColorPickerButton. When changed  `SelectedColor` property, it won't trigger ColorChanged event. So I suppose to just use ColorPicker. That's good.

2023-04-05 15:50 UTC, Poker-sang commented
> ColorPicker (from the Toolkit) doesn't have this issue.

Yes, I just checked it. But they all have binding failure
![%NQ$}FC%PO5I%3850J[0Y11(1).png](https://user-images.githubusercontent.com/62325494/230135014-70484966-c171-4b05-8285-25e750192cc3.png)

So I prefer `Microsoft.UI.Xaml.Controls.ColorPicker`

2023-04-05 16:03 UTC, yaira2 commented
> Microsoft.UI.Xaml.Controls.ColorPicker

The WinUI color picker takes up a lot more space whereas the Toolkits is a lot nicer.

2023-04-05 16:10 UTC, Poker-sang commented
Then I think we'll be fine with the current solution.🤔

2023-04-05 19:20 UTC, Poker-sang commented
> We'll still need to switch back to ColorPicker to fix this issue.

Sorry I didn't get it. The PR is closed and not merged. So it should already be using ColorPicker by now

2023-04-05 20:10 UTC, yaira2 commented
Ah you're right, the issue most be from a different change.