RichCommand: InstallFont
files-community/Files pull request #11780
Opened 2023-03-20 15:01 UTC by mafra99

**Resolved / Related Issues**
- [ ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Relates #11481 

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [x] Are there any other steps that were used to validate these changes?
   1. Install a font from the toolbar
   2. Install a font from the menu flyout
   3. Install button is hidden if no item is selected or in recycle bin

**Screenshots (optional)**
Add screenshots here.

2023-03-21 19:22 UTC, yaira2 commented on src/Files.App/Shell/Win32API.cs
> +		public static void InstallFont(string fontFilePath, bool forAllUsers)
Are these changes related to the rich command? If not, we should limit the scope of this PR.

2023-03-21 19:24 UTC, yaira2 commented on src/Files.App/Actions/Content/InstallFontAction.cs
I think that's fair

2023-03-21 21:02 UTC, ferrariofilippo requested changes
Overall lit ooks good, just one little thing with the style

2023-03-22 10:39 UTC, QuaintMako approved these changes
LGTM

2023-03-22 13:57 UTC, merged