Docs: Added Command list
files-community/Files pull request #11828
Opened 2023-03-24 03:00 UTC by hishitetsu

**Resolved / Related Issues**
- [X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.

2023-03-24 03:08 UTC, yaira2 commented
Once this is finished, we can port it over the to the website repo.

2023-03-24 03:51 UTC, hishitetsu commented
Why is there no hotkey assigned to OpenItem? I believe Enter should be assigned.

2023-03-24 06:35 UTC, hishitetsu commented
I filled in all the descriptions.

2023-03-24 09:36 UTC, QuaintMako commented
@hishitetsu I've added a few commands I forgot in #11481.

2023-03-24 13:13 UTC, hishitetsu commented
Don't worry! If the list is missing an update, I will maintain it.
However, it might be a good idea to add a check to the PR template.

2023-03-26 02:58 UTC, yaira2 commented
Should we leave this open until we finish with the rich command work?

2023-03-26 03:47 UTC, hishitetsu commented
That's also possible. I hope to merge this by the time we start implementing the command palette or shortcut customization.

2023-03-28 05:24 UTC, onein528 requested changes
Please don't add spaces in table.

2023-03-28 05:30 UTC, hishitetsu commented
> Please don't add spaces in table.

You mean '| Category      |' should be '| Category |' for example?

2023-03-28 05:42 UTC, onein528 commented
Yes. and separator should be `---` each

2023-03-28 06:10 UTC, hishitetsu commented
At first I did so, but @yaira2 put in the space. I think it is easier to see it as it is now, but why shouldn't it include spaces?

2023-03-28 06:30 UTC, onein528 commented
This kind indentation will be meaningless even if it is readability.

- When you have to add a new text that has more letters than expected.
- When you have to edit a existing text, you have to adjust spacing.

I also thought this is nice idea before, but it's tiresome.

2023-04-14 17:53 UTC, yaira2 commented
@hishitetsu do you want to add the descriptions to the resource file now? I think we have enough to move forward with this now.

2023-04-14 23:59 UTC, hishitetsu commented
> @hishitetsu do you want to add the descriptions to the resource file? I think we have enough to move forward with this.

Ok, I will do it within a few days.

2023-04-15 10:50 UTC, hishitetsu commented
> Ok, I will do it within a few days.

Done.

2023-04-16 01:39 UTC, yaira2 commented on specs/RichCommand/CommandList.md
Do we still need this file, or should we move the information over to the website documentation?

2023-04-16 05:14 UTC, hishitetsu commented on specs/RichCommand/CommandList.md
I think it depends on whom the website documentation is targeted to, as this document contains information that is not needed by the average user.

2023-04-16 14:27 UTC, yaira2 commented on specs/RichCommand/CommandList.md
The documentation is targeted towards users, but once this PR is merged, we won't need it for ourselves anymore since it already served its purpose of tracking the different actions.

2023-04-16 14:36 UTC, hishitetsu commented on specs/RichCommand/CommandList.md
It may be necessary for the purpose of checking for similar actions already in place if developers want to add actions in the future. However, I leave it to you to decide where to put this.

2023-04-16 14:43 UTC, yaira2 commented on specs/RichCommand/CommandList.md
We can do both, we'll just have to keep the two in sync.

2023-04-16 14:44 UTC, yaira2 approved these changes
LGTM

2023-04-16 14:44 UTC, merged