FIX: a issue where  Show checkboxes when selecting items wasen't applying in the grid layouts
files-community/Files pull request #12229
Opened 2023-04-28 19:01 UTC by Krytan

![proof](https://user-images.githubusercontent.com/42214331/235229881-c0c3cae3-7b4e-4171-b1c8-42cd3c1557bc.png)

**Validation**
How did you test these changes?
1. Turn off option to show checkboxes when selecting items
2. Switch to grid layout
3. Select an item
4. Checkbox is not  visible

2023-04-28 19:03 UTC, yaira2 commented on src/Files.App/Assets/FilesOpenDialog/FilesLauncher.exe
This file shouldn't have been changed, must have been auto generated by Visual Studio.

2023-04-28 19:05 UTC, Krytan commented on src/Files.App/Assets/FilesOpenDialog/FilesLauncher.exe
accidently commited the build version I gonna commit again without it

2023-04-28 23:24 UTC, hishitetsu requested changes
This hides checkboxes even when the checkbox option is on and the item is hovered over. The behavior should not change when the option is on.

@yaira2 do you think checkboxes should not be displayed at all when the option is off? If so, the same modification should be made to the details layout.

2023-04-29 11:39 UTC, Krytan commented
> This hides checkboxes even when the checkbox option is on and the item is hovered over. The behavior should not change when the option is on.
> 
> @yaira2 do you think checkboxes should not be displayed at all when the option is off? If so, the same modification should be made to the details layout.

In not grid layout mode when you turn off the "see checkboxes" settings you don't see the checkbox at all so I suggest the same applying for grid layout otherwise it can be a bit confusing.

I can see hovering in an item is not displaying the checkboxes when the settings are on  that's because I removed the mouse pointer that is also something you don't see in the not grid layout but I guess is something nice to have so I gonna add it back

2023-04-29 13:12 UTC, hishitetsu commented
In the detail layout, a checkbox appears when you hover over a thumbnail. Originally, the checkbox would appear when the cursor was hovered anywhere on the item, but this behavior was changed to the current one in response to user feedback that the thumbnail was frequently hidden.
The current checkbox option determines whether the checkbox is always displayed when an item is selected, and the checkbox feature itself is available whether this option is on or off.

2023-04-29 13:55 UTC, Krytan commented
> In the detail layout, a checkbox appears when you hover over a thumbnail. Originally, the checkbox would appear when the cursor was hovered anywhere on the item, but this behavior was changed to the current one in response to user feedback that the thumbnail was frequently hidden. The current checkbox option determines whether the checkbox is always displayed when an item is selected, and the checkbox feature itself is available whether this option is on or off.

I see I can make the same modifications on details as well so it only show the boxes when the settings to show check-boxes is set and then rename the setting to "show checkboxes" ? and when the setting is ON stick with checkbox is always displayed when an item is selected this seems like a good approach 

the best approach in my opinion would  be in the details layout having the checkbox on the left side of the thumbnail instead of on top of it so the thumbnail doesn't appear hidden when an item is selected it seems that the current option is only useful for detail layout

2023-04-29 16:39 UTC, Krytan commented
![Screenshot 2023-04-29 183708](https://user-images.githubusercontent.com/42214331/235313723-7a473053-5743-418b-8a5b-7080492c078a.png)

I made some modifications so I could show an example of my previous reply

2023-04-30 01:49 UTC, yaira2 commented
@hishitetsu the expected behavior is to still show the checkboxes if the user hovers directly over the checkbox area. The details layout has the correct behavior already, this PR should help the grid layouts have the same behavior.

2023-04-30 02:32 UTC, hishitetsu commented
Okay, so this PR is trying to do something different.
This PR appears to completely disable the checkbox when the option is off.

In the details layout, there are thumbnails as markers for the location of checkboxes, but in the grid layout, there are no markers. If checkboxes are displayed only when the cursor is over the checkbox area, I think users will not know where the checkboxes are.

2023-04-30 11:41 UTC, Krytan commented
Exactly it is confusing when I first used the app I had no idea that in the details layout check boxes are displayed only when the cursor is over the thumbnail/icon I only found out that when explicit explained which makes me believe that  the majority of people won't know that either now for grid layout to have the same behavior it has to have a marker / a checkbox area somewhere.

2023-04-30 14:33 UTC, yaira2 commented
> This PR appears to completely disable the checkbox when the option is off.

I'm not against this idea but I'm with @hishitetsu that we need to apply the same behavior to the details layout.

2023-04-30 16:25 UTC, 0x5bfa reviewed
Can you use XamlStyler? We are currently using a xaml styling extension named XamlStyler and not until you fix annotations by installing following extension, we can approve.

Depends on your visual studio version.
[XamlStyler for 2019](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler)
[XamlStyler for 2022](https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022)

2023-04-30 16:38 UTC, Krytan commented
> 

Thanks I will do that

2023-04-30 17:24 UTC, Krytan commented
![unknown_2023 04 30-17 53](https://user-images.githubusercontent.com/42214331/235366804-703be5b9-6685-4179-ba9d-712f546498bf.png)

To test:
   1. Switch to grid layout
   2. Turn off option to show checkboxes when selecting items
   3. Hover over an item with the cursor (shouldn't show any checkbox until your cursor is in the marker/the checkbox location)
   
Should work just like details layout

2023-04-30 17:28 UTC, yaira2 commented
@Krytan thanks! This is what I was looking for 👍 

If we get feedback that it's still confusing users, we can hide the checkbox on hover as well but I'd like to try it this way first.

2023-04-30 17:32 UTC, yaira2 commented on src/Files.App/Assets/FilesOpenDialog/FilesLauncher.exe
Can you revert this?

2023-04-30 17:32 UTC, yaira2 commented
@Krytan can you apply these changes to the tiles layout as well?

2023-04-30 18:12 UTC, Krytan commented
@yaira2 Tiles should behave the same as well now. I absolutely agree on the idea of taking changes slowly and gathering feedback before making a step. let me know if everything works as intended

2023-04-30 19:42 UTC, yaira2 submitted a review, later dismissed
LGTM

Will merge once the changes to the launcher are reverted.

2023-04-30 20:01 UTC, Krytan commented
Should be good now

2023-04-30 20:23 UTC, yaira2 commented on src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
> +				// Show checkboxes when hovering of the thumbnail (regardless of the setting to hide them)
```suggestion
				// Show checkboxes when hovering over the check box area (regardless of the setting to hide them)
```

2023-04-30 20:35 UTC, yaira2 approved these changes

2023-04-30 22:46 UTC, merged

2023-04-30 22:50 UTC, yaira2 commented
@Krytan thank you, congratulations on your first pull request!

2023-04-30 23:21 UTC, Krytan commented
@yaira2 I have to thank you! going deep on the project and understanding how the code works really was a pleasure experience I can't describe the emotions involved and to be abbe to contribute at the end man I just wanna do more of this!