Fixed: Eject_Option_for_External_Hard_Drives- Bug #13250
files-community/Files pull request #13512
Opened 2023-10-13 01:10 UTC by kworede582

**Resolved / Related Issues**
- [ X] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #issue...Bug: Eject option isn't displayed for external hard drives #13250 

**Validation**
How did you test these changes?
- [X ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [ ] Did you remove any strings from the en-us resource file?
   - [ ] Did you search the solution to see if the string is still being used? 
- [ ] Did you implement any design changes to an existing feature?
   - [ ] Was this change approved?
- [ X] Are there any other steps that were used to validate these changes?
   1. Open app ...
   2. Click settings button ...

**Screenshots (optional)**
**External Hard Drive Eject Option:**
<img width="587" alt="Disk_Drive_Eject" src="https://github.com/files-community/Files/assets/122647305/54fb089f-e197-46e3-a70e-3b560bd7b0af">

**External Hard Drive Properties:**
<img width="587" alt="Fixed_Disk_Drive" src="https://github.com/files-community/Files/assets/122647305/ecf3d0a6-cd12-4575-aa6a-065584dc931d">

2023-10-13 01:15 UTC, yaira2 commented
> Are there any other steps that were used to validate these changes?

Which steps can we use to validate the changes?

2023-10-13 01:16 UTC, yaira2 commented
In addition to displaying the option, did you verify that it works?

2023-10-13 01:21 UTC, kworede582 commented
**Fix Description:** Files app incorrectly categorizes external hard drives as 'Fixed' instead of 'Removable', resulting in lack of the 'Eject' option/property for these drives. 
The fix involves reclassifying external hard drives labeled as 'Fixed' by Files as 'Removable' and implementing a check to differentiate them from the "C:\" drive, thereby enabling the 'Eject' option for external hard drives.

2023-10-13 01:25 UTC, kworede582 commented
> In addition to displaying the option, did you verify that it works?

Yes, verified it. First you check whether it is [external] hard disk drive in the 'Properties'.  and then you can right click and check if you can issue 'Eject'

2023-10-13 01:58 UTC, hishitetsu commented
Fixed drives other than drive C are not necessarily external HDD/SSDs. There may be more than one internal HDD/SSD, or it may be physically one but divided into multiple partitions.

2023-10-25 18:57 UTC, Lukiluc29 commented
I have just tested this fix, and it works well for hard drives. However, my internal hard drives are being recognized as removable.

2023-11-08 22:20 UTC, yaira2 commented
@kworede582

2023-11-09 00:57 UTC, hishitetsu commented
@0x5bfa are you going to fix this along with #13462?

2023-11-09 03:55 UTC, 0x5bfa commented
Yeah, I was, but If @kworede582 can fix, I will leave a review.

2023-11-09 06:33 UTC, 0x5bfa requested changes

2023-11-09 06:33 UTC, 0x5bfa commented on src/Files.App/Data/Items/DriveItem.cs
> +			is_C_Drive = (item.Type == DriveType.Fixed && !(string.Equals(root.Path, "C:\\", StringComparison.OrdinalIgnoreCase)));
What if user's OS-installed drive is not C? Could be any letter though.

2023-11-26 01:04 UTC, yaira2 commented
@kworede582 are you still working on this?

2023-12-11 13:38 UTC, closed without merging