Feature: List all the SharePoint directories
files-community/Files pull request #15070
Opened 2024-03-27 23:57 UTC by mbartlett21

I got a bit annoyed with Files only listing one of the Company SharePoint folders that I use, so I went and implemented this.

**Resolved / Related Issues**
- [x] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
   Closes #4966

**Validation**
How did you test these changes?
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? You can use Accessibility Insights for this.
- [x] Are there any other steps that were used to validate these changes?
   1. Open app
   2. Compare SharePoint listing between old and new versions and between the actual folders.

**Screenshots**
![image](https://github.com/files-community/Files/assets/29034492/541d7a7c-a8c7-433a-a0f2-80b2c87c66a5)

2024-03-28 16:33 UTC, yaira2 commented on src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
> +				}
```suggestion
					continue;
```

2024-03-30 03:30 UTC, 0x5bfa requested changes

2024-03-31 14:50 UTC, yaira2 approved these changes

2024-03-31 21:57 UTC, 0x5bfa approved these changes
Looks nice, codewise.

2024-04-03 22:55 UTC, merged