Feature: Add missing system backdrops
files-community/Files pull request #15406
Opened 2024-05-15 18:07 UTC by heftymouse

This PR adds all the available system backdrop options - None, Mica non-alt, and base Acrylic in addition to the existing Mica and Thin Acrylic (called just Acrylic in the UI) options. Design aside, this is mainly for completeness in theming. Mica Alt is still the default option.

**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- Closes #15045

**Steps used to test these changes**

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

1. Opened Files
2. Tested switching system backdrops
3. Tested switching themes

When switching themes with the system backdrop set to None, the background only updates after a resize or focusing another window. This is an issue with the way WinUI handles repainting the background.

2024-05-15 19:57 UTC, yaira2 commented on src/Files.App/Strings/en-US/Resources.resw
> +    <value>Thin Acrylic</value>
Can you add a comment providing context for translators

2024-05-15 19:57 UTC, yaira2 approved these changes

2024-05-15 21:20 UTC, 0x5bfa requested changes

2024-05-15 21:24 UTC, yaira2 commented on src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
> +			BackdropMaterialTypes.Add(BackdropMaterialType.ThinAcrylic, "ThinAcrylic".GetLocalizedResource());
This sounds like something we can be doing for the other settings view models as well.

2024-05-15 23:22 UTC, yaira2 commented on src/Files.App/Strings/en-US/Resources.resw
> +    <value>Thin Acrylic</value>
```suggestion
    <value>Thin Acrylic</value>
    <comment>This is a type of backdrop for the application background</comment>
```

2024-05-15 23:34 UTC, 0x5bfa commented on src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
> +			BackdropMaterialTypes.Add(BackdropMaterialType.ThinAcrylic, "ThinAcrylic".GetLocalizedResource());
Wait we can't use it for dictionary.
We can use `LocalizedEnumDescriptionFactory` we made when we implemented Layout Picker

2024-05-16 01:26 UTC, 0x5bfa commented on src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
> +			BackdropMaterialTypes.Add(BackdropMaterialType.ThinAcrylic, "ThinAcrylic".GetLocalizedResource());
Please leave as is for now. I’ll make a bulk change.

2024-05-16 01:33 UTC, merged