Fix: Fixed an issue where the forward icon was wrongly clipped
files-community/Files pull request #15490
Opened 2024-05-28 18:25 UTC by 0x5bfa

### Resolved / Related Issues

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.

- https://discord.com/channels/725513575971684472/725514946112127057/1245057778788208691

### Steps used to test these changes

Stability is a top priority for Files and all changes are required to go through testing before being merged into the repo. Please include a list of steps that you used to test this PR.

![image](https://github.com/files-community/Files/assets/62196528/0f8d83c2-51f6-4811-ba53-899204cd36be)

2024-05-28 18:27 UTC, 0x5bfa commented
cc @XTorLukas

2024-05-28 19:24 UTC, XTorLukas commented
Tested and bug fixed 😊

2024-05-28 19:27 UTC, XTorLukas approved these changes
LGTM

2024-05-28 19:43 UTC, 0x5bfa commented
Thank you!

2024-05-28 20:01 UTC, yaira2 commented
What are the steps to repro this issue?

2024-05-28 21:24 UTC, heftymouse requested changes
the icons are now hidden for most of the swipe gesture, they only appear at the very end after 64 pixels. this is a regression that makes it feel a lot less responsive to use

instead, a simpler fix would be to only increase the offset in the expression animation from 48 to something like 52, this would push it off the side of the pane by a few pixels. I've tested this and can confirm it works and keeps all of the existing behaviour.

2024-05-28 21:29 UTC, XTorLukas commented
All changes can be deleted, the solution is just to set the margin here:

https://github.com/files-community/Files/blob/f3e2d2a895ca244c22197e8d4a16285bac6372a9/src/Files.App/Views/Shells/ModernShellPage.xaml#L57

```
Margin="-1,0,4,0"
```

https://github.com/files-community/Files/blob/f3e2d2a895ca244c22197e8d4a16285bac6372a9/src/Files.App/Views/Shells/ModernShellPage.xaml#L78

```
Margin="1,0,-4,0"
```

2024-05-28 21:37 UTC, heftymouse commented
amazing, even better! the 1 and -1 can probably be removed too

2024-05-28 21:43 UTC, XTorLukas commented
No -1 and 1 must remain here, the problem would then occur on the other side
Prevents the problem on this side
![image](https://github.com/files-community/Files/assets/84145589/e0a72641-ce1e-4b3b-999c-8a3a32d4ce89)

2024-05-28 22:24 UTC, heftymouse commented
sorry, i mean like `-4,0,0,0` and `0,0,-4,0`

2024-05-28 22:45 UTC, XTorLukas commented
> sorry, i mean like `-4,0,0,0` and `0,0,-4,0`

Yes, that's enough. I think it's more elegant.

2024-05-29 09:54 UTC, XTorLukas approved these changes
LGTM, It's simple, but it's work.

2024-05-29 10:57 UTC, heftymouse approved these changes

2024-05-29 14:34 UTC, merged