Add support for shortcut files
files-community/Files pull request #1573
Opened 2020-07-25 18:58 UTC by gave92

This PR adds support for shortcut files (".lnk", ".url")
Related issue: #177

**What works**
- Viewing shortcuts with thumbnail
- Opening file shortcuts
- Navigating to destination when opening a shortcut to a folder (also open in new tab/window)
- Deleting shortcuts (but can't send to recycle bin)
- Renaming shortcuts
- Dropping a file inside a folder shortcut

**What doesn't work**
- Copy/Move shortcuts

@duke7553 I'm not sure if the remaining points can be solved: copy/move operations require a StorageFile but StorageFile APIs will throw UnauthorizedAccessException on shortcuts. Renaming and deleting work using the **FromApp methods.

2020-07-26 03:54 UTC, Jaiganeshkumaran commented
@gave92 You can't share a shortcut file even in Explorer but for .URL files we could share the link of the shortcut.

2020-07-26 04:50 UTC, Jaiganeshkumaran commented
Is is possible to create new shortcut files with this PR?

2020-07-26 08:35 UTC, gave92 commented
@Jaiganeshkumaran I have yet to look into creating new shortcuts, currently you can only view and use existing ones. Ideally you should be able to create new shortcuts and edit existing ones in the Property window.

2020-07-26 09:21 UTC, Jaiganeshkumaran commented
@gave92 Don't share anything for LNK files since they mostly contain a local path and sharing it doesn't make sense unless the path is accessible from other PCs.

2020-07-26 11:19 UTC, gave92 commented
@Jaiganeshkumaran now you can create shortcuts to files and folders from right-click context menu :)

2020-07-26 11:44 UTC, Jaiganeshkumaran commented
Can you create a shortcut from a selected folder? Please add an option to create shortcut from selected folder.

2020-07-26 11:52 UTC, gave92 commented
@Jaiganeshkumaran yes you can already do that

2020-07-26 14:35 UTC, gave92 commented
Would you consider something like this for the Property windows?

![image](https://user-images.githubusercontent.com/9673091/88481831-fbb3e380-cf5d-11ea-8b1a-05107e8e8e08.png)

2020-07-26 16:00 UTC, duke7553 commented
@gave92 Sorry I couldn't get to this one earlier. 

To answer your questions:
- We would not want to use a TabView for Static navigation. A Pivot-like control is probably more suited for this scenario.
- Our goal is to switch over to exclusively use the *FromApp methods for File operations, which I haven't got around to yet.

Thank you for your work on this.

2020-07-26 16:21 UTC, yaichenbaum commented
> Would you consider something like this for the Property windows?
> 
> <img alt="" width="350" src="https://user-images.githubusercontent.com/9673091/88481831-fbb3e380-cf5d-11ea-8b1a-05107e8e8e08.png">

As @duke7553 mentioned, we would probably want to use something like a horizontal navigation menu here.

2020-07-26 16:23 UTC, gave92 commented
@yaichenbaum So somethink like [Pivot](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pivot) or [horizontal NavigationView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview) corrent?

2020-07-26 16:27 UTC, XPoppyX commented
@gave92 what about this icon?

![Anotación 2020-07-26 122526](https://user-images.githubusercontent.com/61259627/88484254-35272780-cf3b-11ea-8bee-c0bbbf1cb68c.png)

2020-07-26 16:46 UTC, yaichenbaum commented
> @yaichenbaum So something like [Pivot](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pivot) or [horizontal NavigationView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview) correct?

If I recall correctly, it's recommended to use the NavigationView over the Pivot control.

2020-07-26 16:57 UTC, XPoppyX commented
steam game shortcuts are shown with this icon, instead of the game icon
![Anotación 2020-07-26 125627](https://user-images.githubusercontent.com/61259627/88484804-7de0df80-cf3f-11ea-84f8-33c04a597705.png)

2020-07-26 16:59 UTC, gave92 commented
@XPoppyX I can confirm that at the moment ".url" files won't display the proper icon

2020-07-26 17:15 UTC, XPoppyX commented
I have tested the new icon but with reduced size:

**GridView:** 28 => 18

**TilesView:** 22 => 15

![Anotación 2020-07-26 130725](https://user-images.githubusercontent.com/61259627/88485073-43784200-cf41-11ea-8821-3148e0610900.png)

I think the current size is somewhat big

2020-07-26 18:36 UTC, XPoppyX commented
@gave92 Check your repository, I added a PR

2020-07-26 18:39 UTC, gave92 commented
@XPoppyX thanks a lot!

2020-07-26 18:43 UTC, XPoppyX commented
what about md5hash?
![Anotación 2020-07-26 144251](https://user-images.githubusercontent.com/61259627/88486809-62310580-cf4e-11ea-9aee-14b214cfb9d9.png)

2020-07-26 18:44 UTC, gave92 commented
I take it doesn't work? Only on shortcuts or everywhere?

2020-07-26 18:45 UTC, XPoppyX commented
only on shortcuts

2020-07-26 18:53 UTC, gave92 commented
@XPoppyX should be fixed, note that it will be the hash of the shortcut `target` and not of the shortcut itself

2020-07-26 21:20 UTC, XPoppyX commented
icon proposal
![Anotación 2020-07-26 171619](https://user-images.githubusercontent.com/61259627/88489682-c4e0cc00-cf63-11ea-92aa-3fc3f0ef59a4.png)

2020-07-26 23:10 UTC, XPoppyX commented
- in "Shortcut" tab, for exe files it should display as "Application" type instead of just "file"
- in "General" tab, the type does not display correctly in my language:
![Anotación 2020-07-26 185500](https://user-images.githubusercontent.com/61259627/88491649-65d68380-cf72-11ea-822a-adfedae12f9b.png)
_this also happens in tiles view, see:_ #843
- Is it okay to display the type as "Ink File" instead of "Shortcut (.Ink)"?

2020-07-27 01:46 UTC, Jaiganeshkumaran commented
> * Is it okay to display the type as "Ink File" instead of "Shortcut (.Ink)"?

No, it's not. Not everyone knows what the INK extension means.

2020-07-27 20:40 UTC, gave92 commented
@XPoppyX most of your notes should now be fixed:
- icon proposal --> done!
- in "Shortcut" tab, for exe files it should display as "Application" type instead of just "file" --> done!
- in "General" tab, the type does not display correctly in my language: --> done (needs resource translation/only for shortcuts)
- Is it okay to display the type as "Ink File" instead of "Shortcut (.Ink)"? --> done (needs resource translation)

2020-07-27 20:41 UTC, XPoppyX commented
nice

2020-07-28 20:55 UTC, tsvietOK commented on Files/Views/Pages/Properties.xaml.cs
> +            AppSettings.ThemeModeChanged += AppSettings_ThemeModeChanged;
To fix black window controls (minimize, maximize, close) move `AppSettings.ThemeModeChanged += AppSettings_ThemeModeChanged;` before if in this method.

2020-07-28 21:03 UTC, tsvietOK commented
Can you increase Properties window height from 475 to 550?

2020-07-28 21:35 UTC, tsvietOK requested changes
Disable MD5 has calculation for link item, as it is hash of the real file, not the link file.

2020-07-28 22:35 UTC, tsvietOK commented
@gave92 Why did you removed "Created" and "Accessed" fields for link files?

2020-07-29 05:23 UTC, gave92 commented
@tsvietOK both were of the link target and not of the link itself (same as the md5 hash)

2020-07-29 16:18 UTC, tsvietOK commented
Is it possible to to don't display link file extension independently from "Show file extension" setting?

2020-07-29 16:31 UTC, tsvietOK requested changes

2020-07-29 16:31 UTC, tsvietOK commented on Files/Interacts/Interaction.cs
> +                        { "filepath", Path.Combine(CurrentInstance.FilesystemViewModel.WorkingDirectory, selectedItem.ItemName + " - shortcut" + ".lnk") }
Add ability to translate " - shortcut"

2020-07-29 23:45 UTC, tsvietOK submitted a review, later dismissed

2020-07-30 00:02 UTC, yair100 requested changes

2020-07-30 01:17 UTC, yair100 approved these changes

2020-07-30 01:18 UTC, merged