Fix: Arm support. Small performance optimization.
files-community/Files pull request #16523
Opened 2024-11-24 20:53 UTC by viruseg

New comparator is slightly faster than [DllImport(“api-ms-win-core-string-l1-1-0.dll”)].CompareStringEx. And supports Arm. Previously, a string comparer was used for Arm without proper support for natural comparison.

| Method                                 | Mean     | Error     | StdDev    | Allocated |
|--------------------------------------- |---------:|----------:|----------:|----------:|
| Test_api-ms-win-core-string-l1-1-0.dll | 1.185 ms | 0.0095 ms | 0.0084 ms |      89 B |
| Test_NaturalComparer                   | 1.072 ms | 0.0073 ms | 0.0065 ms |      89 B |

2024-11-25 00:12 UTC, yaira2 commented
@XTorLukas fyi

2024-11-26 22:54 UTC, Imran-imtiaz48 reviewed
Strengths:
1.	Code Structure:
o	The overall structure is clean and follows good practices. Separating the logic into different Compare overloads makes the functionality clear and modular.
o	Usage of sealed for NaturalComparer is excellent as it enforces immutability and ensures that no one can derive further classes from it.
2.	Natural Sorting:
o	The natural sorting logic is well-implemented. Handling numeric values and trimming leading zeros demonstrates attention to detail for real-world comparisons.
3.	Extensibility:
o	The inclusion of multiple IComparer implementations for objects, strings, and memory spans makes the class highly reusable in diverse scenarios.
4.	Performance Optimization:
o	Use of ReadOnlySpan<char> for comparisons is a nice touch, ensuring memory efficiency and reducing allocations.
Suggestions for Improvement:
1.	Error Handling:
o	It might be useful to add some error handling or documentation on expected behavior for edge cases, such as comparing incompatible object types that are not strings or IComparable.
2.	Code Duplication:
o	The logic in Compare(string? x, string? y) and Compare(ReadOnlyMemory<char> x, ReadOnlyMemory<char> y) is nearly identical. Consider consolidating them to avoid duplication, perhaps by internally calling the Span overload.
3.	Test Coverage:
o	While the logic is robust, it’s important to ensure this is accompanied by comprehensive test cases to verify behavior across a variety of inputs: 
	Strings with leading/trailing spaces.
	Numeric strings of varying lengths.
	Mixed strings with numbers and letters (e.g., abc123 vs abc23).
4.	Default Behavior:
o	Consider documenting or adding a safeguard for cases where x or y are not string or IComparable. Right now, it defaults to StringComparer.FromComparison, which might lead to unexpected results.
5.	Inline Documentation:
o	While the code is clear, inline comments explaining some of the more complex parts (e.g., CompareNumValues logic for leading zeros) would improve readability for future maintainers.
6.	Static Default:
o	Instead of instantiating NaturalComparer multiple times, you could provide a static readonly instance for common comparisons (e.g., Ordinal).
Code Example for Consolidation:
Here’s how you could consolidate the Compare methods:
public int Compare(ReadOnlyMemory<char> x, ReadOnlyMemory<char> y) 
    => Compare(x.Span, y.Span, stringComparison);

public int Compare(string? x, string? y) 
    => Compare(x.AsSpan(), y.AsSpan(), stringComparison);

Summary
This is a solid implementation of a natural comparer with attention to edge cases like leading zeros and numeric sorting. A few tweaks around code reuse, documentation, and test coverage would make it even better. Great job overall.

2024-11-27 08:54 UTC, catuhana commented on src/Files.App/Helpers/NaturalStringComparer.cs
> +
Whitespace left here.

2024-11-27 09:32 UTC, 0x5bfa requested changes

2024-11-27 09:32 UTC, 0x5bfa commented on src/Files.App/Helpers/NaturalStringComparer.cs
> +		private sealed class NaturalComparer : IComparer<object?>, IComparer<string?>, IComparer<ReadOnlyMemory<char>>
Can you add xml comment on this class so others can understand what this is doing under the hood.

2024-11-27 09:32 UTC, 0x5bfa commented on src/Files.App/Helpers/NaturalStringComparer.cs
> +		        return numValue2.Length < numValue1.Length ? -1 : 1; // "033" < "33" === true
```suggestion
		        return numValue2.Length < numValue1.Length ? -1 : 1; // "033" < "33" == true
```

2024-12-11 05:38 UTC, 0x5bfa commented
FYI, this isn't yet published and documented but C# runtime just superseded `CompareOptions.NumericOrdering` 2 weeks ago.

2024-12-11 05:43 UTC, 0x5bfa commented
FYI, C# runtime just superseded this with `CompareOptions.NumericOrdering` 2 weeks ago (not documented yet).

2024-12-12 04:03 UTC, 0x5bfa commented
C# runtime implemented SortOptions.NumericOrdering just two weeks ago. We will use it once we upgrade to NET 9.x, instead.

2024-12-15 16:05 UTC, yaira2 approved these changes
LGTM

2024-12-15 16:05 UTC, merged