Feature: Added support for Lucid Link v3
files-community/Files pull request #16594
Opened 2024-12-10 19:37 UTC by Lamparter

**Resolved / Related Issues**

- Closes #16586

2024-12-11 16:16 UTC, yaira2 commented on src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
> +					if (IsSymlink(directory))
It seems like the symlink is one directory deeper, so this will return false.

2024-12-13 12:12 UTC, Josh65-2201 requested changes
The old method can be removed as both v2 and v3 will access it from the volumes folder. You would also need to search 1 layer sub folders for the system link. Volumes/Workspace/filespace (the system link) is how it's formatted.

2024-12-24 17:49 UTC, Josh65-2201 commented
The workspace and filespace path are backwards so it always returns not a folder

2024-12-24 18:00 UTC, Josh65-2201 approved these changes

2024-12-24 19:42 UTC, yaira2 commented on src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
> +				if (IsSymlink(subDirectory))
```suggestion
				if (Win32Helper.HasFileAttribute(subDirectory, System.IO.FileAttributes.ReparsePoint))
```

2024-12-24 19:59 UTC, yaira2 reviewed
`private static bool IsSymlink` can be removed

2024-12-24 20:02 UTC, yaira2 approved these changes

2024-12-24 20:03 UTC, merged