Feature: Improved performance when opening path bar flyouts
files-community/Files pull request #16665
Opened 2024-12-31 21:28 UTC by yaira2

**Resolved / Related Issues**

To prevent extra work, all changes to the Files codebase must link to an approved issue marked as `Ready to build`. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
- For #4180

**Steps used to test these changes**

1. Navigated between multiple folders until the back & forward stack contained a bunch of items
2. Right clicked the back and forward buttons
3. Confirmed the thumbnails are 'lazy' loaded
4. Clicked the expand chevron on the path bar and confirmed the menu flyout opens quicker

2025-01-01 15:57 UTC, d2dyno1 requested changes

2025-01-01 15:57 UTC, d2dyno1 commented on src/Files.App/Data/EventArguments/ToolbarFlyoutOpeningEventArgs.cs
> +		public MenuFlyout OpeningFlyout { get; set; }
Make this get; only and inject through a constructor

2025-01-02 16:29 UTC, Josh65-2201 commented
Is the files app launcher suppose to be changed in this?

2025-01-02 16:40 UTC, yaira2 commented
Yes, I forgot to update them with https://github.com/files-community/Files/commit/8436c6d574dda2fb1f72a7fc26bdd1bf752031a7

2025-01-02 21:44 UTC, merged