More Precise Exception Handling for Item Rename Operation
files-community/Files pull request #1793
Opened 2020-08-23 18:29 UTC by duke7553

As per [this](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.renameasync?view=winrt-19041#Windows_Storage_StorageFile_RenameAsync_System_String_) documentation, we now handle the following cases during the rename operation to provide specific user feedback through the standard content dialog:

- ArgumentException - equivalent of E_INVALIDARG
- PathTooLongException - equivalent of ERROR_FILENAME_EXCED_RANGE
- FileNotFoundException - equivalent of ERROR_FILE_NOT_FOUND

2020-08-25 23:21 UTC, tsvietOK approved these changes

2020-08-26 01:38 UTC, duke7553 commented
I may have messed up the resources, so I'll have to revert the merge conflict resolution when I get a chance.

2020-09-21 19:45 UTC, yaichenbaum commented
/azp run

2020-09-21 19:46 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +    <value>Item name was too long</value>
```suggestion
    <value>Item name was too long</value>
</data>
```

2020-09-21 19:51 UTC, yaichenbaum requested changes

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.es-ES.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.fr-FR.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.he-IL.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.hi-IN.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.it-IT.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.nl-NL.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.or-IN.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.pl-PL.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.pt-BR.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.ru-RU.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.zh-Hans.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.uk-UA.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.tr-TR.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:51 UTC, yaichenbaum commented on Files/MultilingualResources/Files.ta.xlf
> +          <target state="new">Item name was too long</target>
```suggestion
          <target state="new">Item name was too long</target>
        </trans-unit>
```

2020-09-21 19:55 UTC, yaichenbaum submitted a review, later dismissed

2020-09-24 00:04 UTC, yaichenbaum approved these changes

2020-09-24 00:13 UTC, tsvietOK approved these changes

2020-09-24 00:40 UTC, merged