Fixed an issue where screen readers will wrongly read files and folders as Files.Filesystem.ListedItem
files-community/Files pull request #2177
Opened 2020-10-30 08:45 UTC by Jaiganeshkumaran

Note: This doesn't work in DataGrid

2020-10-30 12:24 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +  </data>
```suggestion
  <data name="FileItemAutomation" xml:space="preserve">
    <value>File</value>
  </data>
  <data name="FolderItemAutomation" xml:space="preserve">
    <value>Folder</value>
  </data>
  <data name="RecycleBinItemAutomation" xml:space="preserve">
    <value>Recycle bin item</value>
  </data>
  <data name="ShortcutItemAutomation" xml:space="preserve">
    <value>Shortcut item</value>
  </data>
```

2020-10-30 14:24 UTC, yaichenbaum commented
Can you please update the genereated resource files?

2020-11-05 14:33 UTC, yaichenbaum requested changes

2020-11-05 14:33 UTC, yaichenbaum commented on Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="new">Show recent files on the home page</targe
```suggestion
          <target state="new">Show recent files on the home page</target>
```

2020-11-05 14:33 UTC, yaichenbaum commented on Files/MultilingualResources/Files.nl-NL.xlf
> +          <target state="new">shortcut item</target
```suggestion
          <target state="new">shortcut item</target>
```

2020-11-05 14:33 UTC, yaichenbaum commented on Files/MultilingualResources/Files.or-IN.xlf
> +          <target state="new">Show recent files on the home page</targe
```suggestion
          <target state="new">Show recent files on the home page</target>
```

2020-11-05 14:33 UTC, yaichenbaum commented on Files/MultilingualResources/Files.pt-BR.xlf
> +        <trans-unit id="SettingsWidgetsShowLibraryCards.AutomationProperties.Name" translate="yes" xml:space="preserve">11
```suggestion
        <trans-unit id="SettingsWidgetsShowLibraryCards.AutomationProperties.Name" translate="yes" xml:space="preserve">
```

2020-11-05 15:20 UTC, yaichenbaum commented on Files/MultilingualResources/Files.or-IN.xlf
> -        </trans-unit>
It looks like this was removed by mistake in several files.

2020-11-05 16:32 UTC, yaichenbaum commented
@Jaiganeshkumaran Can you fix the generated files so that they are up to date?

2020-11-06 03:53 UTC, yaichenbaum approved these changes, later dismissed

2020-11-06 13:48 UTC, yaichenbaum commented
@Jaiganeshkumaran Can you solve the merge conflicts?

2020-11-06 13:51 UTC, Jaiganeshkumaran commented
@yaichenbaum Done

2020-11-06 13:54 UTC, yaichenbaum approved these changes

2020-11-06 16:36 UTC, merged