Finished the german translation
files-community/Files pull request #2199
Opened 2020-11-01 19:52 UTC by JohnnyJTH

Finished the German translation. It was nearly done but I added the last ones.

2020-11-01 21:45 UTC, tsvietOK requested changes

2020-11-01 21:45 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
Is it needed?

2020-11-01 21:45 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
Is it needed?

2020-11-06 11:17 UTC, JohnnyJTH commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
> Is it needed?

What do you mean?

2020-11-15 17:06 UTC, tsvietOK requested changes

2020-11-15 17:06 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
If translation has been verified, these both notes should be removed.

2020-11-15 17:06 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
If translation has been verified, these both notes should be removed.

2020-11-15 17:07 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4">It is accurate</note>
And resolve conflicts, please.

2020-11-18 17:12 UTC, closed without merging