Fixed an issue where clicking the back button in tablet mode wouldn't work
files-community/Files pull request #2459
Opened 2020-11-27 02:22 UTC by yaichenbaum

Fixes #1682

2020-11-27 17:32 UTC, gave92 approved these changes

2020-11-27 17:34 UTC, gave92 requested changes

2020-11-27 17:34 UTC, gave92 commented on Files/Views/Settings.xaml.cs
> +                e.Handled = true;
Will throw null exception

2020-11-27 18:21 UTC, d2dyno1 commented on Files/Views/Settings.xaml.cs
> +                e.Handled = true;
`e?.Handled = true;` should do it

2020-11-28 18:25 UTC, gave92 approved these changes

2020-11-28 23:25 UTC, merged