Increased max GridView size
files-community/Files pull request #2561
Opened 2020-12-08 18:47 UTC by Dylan-Osborne

Fixes #2560

Allows a user to use _ctrl + scroll_ or _ctrl + +_ to resize the GridView to larger than the "Grid View (Large)" default. No new menu option is added and no changes are made to the existing menu sizes.

Max before:
![Max 220](https://user-images.githubusercontent.com/46000533/101526738-b71d6780-3995-11eb-94f0-7ec000ff7e42.jpg)

Max after:
![Max 320](https://user-images.githubusercontent.com/46000533/101526776-c6041a00-3995-11eb-951a-2742755a77bd.jpg)

2020-12-08 20:17 UTC, yaichenbaum requested changes

2020-12-08 20:17 UTC, yaichenbaum commented on Files/Constants.cs
> +                public const int GridViewSizeMax = 320; // Max achievable ctrl + scroll, not a default layout size.
```suggestion
                public const int GridViewSizeMax = 300; // Max achievable ctrl + scroll, not a default layout size.
```

2020-12-09 04:38 UTC, Dylan-Osborne commented on Files/Constants.cs
> +                public const int GridViewSizeMax = 320; // Max achievable ctrl + scroll, not a default layout size.
Updated to 300 as requested

2020-12-09 04:41 UTC, Dylan-Osborne commented
@yaichenbaum If I remember correctly, you wanted the sizes to be multiples of 4, do you also want the GridView size increments to be a multiple of 4 e.g. 20 instead of the 25 it currently is?
https://github.com/files-community/Files/blob/e0da5d6482a4e35d7bdfd23cb49d82c1c054d3b4/Files/BaseLayout.cs#L748
https://github.com/files-community/Files/blob/e0da5d6482a4e35d7bdfd23cb49d82c1c054d3b4/Files/BaseLayout.cs#L757

2020-12-09 04:49 UTC, yaichenbaum commented
> @yaichenbaum If I remember correctly, you wanted the sizes to be multiples of 4, do you also want the GridView size increments to be a multiple of 4 e.g. 20 instead of the 25 it currently is?
> https://github.com/files-community/Files/blob/e0da5d6482a4e35d7bdfd23cb49d82c1c054d3b4/Files/BaseLayout.cs#L748
> 
> 
> https://github.com/files-community/Files/blob/e0da5d6482a4e35d7bdfd23cb49d82c1c054d3b4/Files/BaseLayout.cs#L757

Can you change that to `24`?

2020-12-09 05:48 UTC, Dylan-Osborne commented
@yaichenbaum I can do so, but is there a specific reasoning for 24? Remember that the allowed sizes range from 100 to 300 and 24 isn't a multiple of any of them which means if you choose a default and then _crtl + scroll_ to adjust you may end up with an odd final adjustment like this:
![24](https://user-images.githubusercontent.com/46000533/101589987-36d91f80-39f2-11eb-9276-65b9a6a2d593.gif)
whereas an increment of 20 is smooth to the largest possible size achievable by _ctrl + scroll_
![20](https://user-images.githubusercontent.com/46000533/101590014-45bfd200-39f2-11eb-9ed9-c26918135c2d.gif)

Basically the sizing with 24 works as follows:
220 (default size) --> 244 --> 268 -> 292 --> 316 --> 320 (max is capped at 320)
while 20 is consistent to the end:
220 --> 240 --> 260 --> 280 --> 300 --> 320 (max)

2020-12-09 18:36 UTC, yaichenbaum commented
@Dylan-Osborne Good catch, let's go with 20.

2020-12-09 18:42 UTC, mdtauk commented
Will there be consistent naming with the various set values of Icon Sizes, now they have changed.

What about providing a slider in the context menus, with ticks for the set sizes?

2020-12-09 18:51 UTC, Dylan-Osborne commented
@yaichenbaum Thanks, I've set the increment to 20

@mdtauk The changes in this PR are only accessible by using _ctrl + +_ and _ctrl + scroll_ to fine tune the GridView size. The existing default GridView sizes accessible from the layout flyouts remain the same (small, medium and large). So there's no naming that should need to change.

2020-12-09 18:57 UTC, yaichenbaum commented
> Will there be consistent naming with the various set values of Icon Sizes, now they have changed.
> 
> What about providing a slider in the context menus, with ticks for the set sizes?

@mdtauk Can you open a new proposal for this? Luke started work on a concept a couple of months ago that's similar to what you are describing.
![image](https://user-images.githubusercontent.com/39923744/101674400-6f92ec00-3a26-11eb-8d6f-23b2a3c75219.png)

2020-12-09 18:58 UTC, yaichenbaum approved these changes

2020-12-09 19:26 UTC, mdtauk commented
> > Will there be consistent naming with the various set values of Icon Sizes, now they have changed.
> > What about providing a slider in the context menus, with ticks for the set sizes?
> 
> @mdtauk Can you open a new proposal for this? Luke started work on a concept a couple of months ago that's similar to what you are describing.
> ![image](https://user-images.githubusercontent.com/39923744/101674400-6f92ec00-3a26-11eb-8d6f-23b2a3c75219.png)

#2575

2020-12-09 20:14 UTC, merged