Translation Update [es-ES] + Fix
files-community/Files pull request #3264
Opened 2021-01-24 15:19 UTC by XPoppyX

- New strings translated into Spanish
- Fixed two IDs that were incomplete in string resources
- Added missing string for "Show Bundles on the home page"

2021-01-24 22:02 UTC, tsvietOK requested changes
Resolve conflicts, please.

2021-01-24 22:18 UTC, tsvietOK commented on Files/MultilingualResources/Files.cs-CZ.xlf
> +          <target state="new">Show Bundles on the home page</target>
Missing closing tag.

2021-01-24 22:24 UTC, XPoppyX commented on Files/MultilingualResources/Files.cs-CZ.xlf
> +          <target state="new">Show Bundles on the home page</target>
I'm on it

2021-01-25 20:52 UTC, tsvietOK approved these changes

2021-01-26 00:14 UTC, merged