Fix build and update translation
files-community/Files pull request #3455
Opened 2021-02-05 18:47 UTC by tsvietOK

2021-02-05 19:52 UTC, d2dyno1 requested changes

2021-02-05 19:52 UTC, d2dyno1 commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <source>Enable multiselect options (currently only abailable in the tiles and grid view layout modes)</source>
`abailable` typo

2021-02-05 19:53 UTC, d2dyno1 commented on Files/MultilingualResources/Files.ko-KR.xlf
> +          <source>Enable multiselect options (currently only abailable in the tiles and grid view layout modes)</source>
same here

2021-02-05 20:30 UTC, tsvietOK commented on Files/MultilingualResources/Files.de-DE.xlf
> +          <source>Enable multiselect options (currently only abailable in the tiles and grid view layout modes)</source>
Thank you!

2021-02-05 22:33 UTC, d2dyno1 approved these changes

2021-02-06 13:02 UTC, gave92 approved these changes

2021-02-07 01:03 UTC, yaichenbaum approved these changes

2021-02-07 01:03 UTC, merged