Added the option to close tabs to right
files-community/Files pull request #3929
Opened 2021-03-10 08:51 UTC by d2dyno1

For #260

2021-03-10 16:13 UTC, yaichenbaum commented
@d2dyno1 Can you disable the close tabs to right menu item when the user right clicks on the right-most tab?

2021-03-10 16:14 UTC, yair100 requested changes

2021-03-10 16:44 UTC, d2dyno1 reviewed
Added suggestions

2021-03-10 16:48 UTC, yaichenbaum requested changes

2021-03-10 16:48 UTC, yaichenbaum commented on Files/Views/MainPage.xaml.cs
> +        public static async void CloseTabsToRight(object sender, RoutedEventArgs e)
```suggestion
        public static async void CloseTabsToTheRight(object sender, RoutedEventArgs e)
```

2021-03-10 16:48 UTC, yaichenbaum commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                            Click="{x:Bind views:MainPage.CloseTabsToRight}"
```suggestion
                            Click="{x:Bind views:MainPage.CloseTabsToTheRight}"
```

2021-03-10 16:48 UTC, yaichenbaum commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                        </MenuFlyoutItem>
```suggestion
                            Text="Close tabs to the right"/>
```

2021-03-10 18:09 UTC, d2dyno1 commented
@yaichenbaum :+1:

2021-03-10 20:03 UTC, d2dyno1 commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                        </MenuFlyoutItem>
Should I remove the icon? @yaichenbaum

2021-03-10 20:07 UTC, yaichenbaum commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                        </MenuFlyoutItem>
> Should I remove the icon? @yaichenbaum

Yes, please.

2021-03-10 20:18 UTC, d2dyno1 commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                        </MenuFlyoutItem>
> > Should I remove the icon? @yaichenbaum
> 
> Yes, please.

It's gone, reduced to atoms.

2021-03-10 20:21 UTC, yaichenbaum approved these changes
Great work! LGTM

2021-03-10 20:37 UTC, merged

2021-03-12 09:19 UTC, kal1ms approved these changes