Right clicking on a library unpin them and that's not the correct behaviour
files-community/Files pull request #3946
Opened 2021-03-10 19:27 UTC by oleitao

Right clicking on a library item shows the option to unpin them and that's not the correct behaviour. With that PR i want to correct that issue.

2021-03-10 19:33 UTC, yaichenbaum commented
@gave92 Do you think this scales better than the solution we currently use for this?

2021-03-10 19:49 UTC, gave92 commented
I like the idea of adding a `Section` property to sidebar items so you don't have to write ugly code such as:
```cs
var isLibrary = (MainPage.SideBarItems.FirstOrDefault(x => x.Text == "SidebarLibraries".GetLocalized()) as LocationItem)?.ChildItems?.Contains(item) ?? false;
```
Adding the possibility to unpin single libraries from the section might be less important,

2021-03-10 22:31 UTC, oleitao commented
> I like the idea of adding a `Section` property to sidebar items so you don't have to write ugly code such as:
> 
> ```cs
> var isLibrary = (MainPage.SideBarItems.FirstOrDefault(x => x.Text == "SidebarLibraries".GetLocalized()) as LocationItem)?.ChildItems?.Contains(item) ?? false;
> ```
> 
> Adding the possibility to unpin single libraries from the section might be less important (if we do we could just have left all items under quick access).

Can i continue that development?

2021-03-11 21:33 UTC, gave92 commented
> Can i continue that development?

@yaichenbaum what do you think about allowing users to unpin single library folders? Personal opinion: not needed.

2021-03-11 21:38 UTC, yaichenbaum commented
@gave92 Perhaps we can add an option to delete libraries when we add proper detection for libraries created in File Explorer.

2021-03-11 21:43 UTC, gave92 commented
@oleitao For now we'd limit thie changes to the following:
- Adding the `Section` property to LocationItem
- Use the new property to simplify [this code](https://github.com/files-community/Files/blob/0f1800e007694373712517adf24506a4e6485f5c/Files/UserControls/SidebarControl.xaml.cs#L241)

2021-03-12 23:43 UTC, oleitao commented
> @oleitao For now we'd limit the changes to the following:
> 
> * Adding the `Section` property to LocationItem (~only to LocationItem, INavigationControlItem does not probably need this~edit: current solution is good)
> * Using the new property to simplify [this code](https://github.com/files-community/Files/blob/0f1800e007694373712517adf24506a4e6485f5c/Files/UserControls/SidebarControl.xaml.cs#L241)

@gave92 please check my last commit and tell me if it's everything fine to continue this development?

2021-03-12 23:47 UTC, gave92 requested changes

2021-03-12 23:47 UTC, gave92 commented on Files/App.xaml.cs
> +                    SidebarPinnedController.Model.RemoveLibraryItem(RightClickedItem.Path.ToString());
For now we have decided to not allow to unpin single libraries.

2021-03-12 23:47 UTC, gave92 commented on Files/DataModels/SidebarPinnedModel.cs
> +        public void RemoveLibraryItem(string path)
For now we have decided to not allow to unpin single libraries.

2021-03-13 11:10 UTC, gave92 commented
@oleitao I've pushed here a commit to update the PR to latest main branch. This looks ready to be merged, or is there still something you're planning to add?

2021-03-13 11:14 UTC, gave92 approved these changes

2021-03-13 13:29 UTC, oleitao commented
> @oleitao I've pushed here a commit to update the PR to latest main branch. This looks ready to be merged, or is there still something you're planning to add?

To me it's fine, you can merge.

2021-03-14 00:38 UTC, yaichenbaum approved these changes

2021-03-14 00:39 UTC, merged