Show file hashes in properties like HashTab. #3722
files-community/Files pull request #4300
Opened 2021-03-25 15:22 UTC by oleitao

**Resolved / Related Issues**
This PR is used to implement a new feature to show file hashs MD5/SHA1/CRC32 on Properties panel and compare the current hashs with hashs of another files.

**Validation**
- [x] Get folder Properties and get his hashs
- [x] Compare the current file hashs with other file hashes (check if they are different)
- [x] Compare the current file hashs with same file hashes (check if they are equals)

**Screenshots (optional)**
![hashs](https://user-images.githubusercontent.com/72361786/112497253-5a479080-8d7d-11eb-863f-4db72e6cdc57.PNG)

2021-03-25 15:50 UTC, yaichenbaum commented
@oleitao Do you really think we should include the option to compare with other Files? I think the properties dialog should be limited to the selected file.

2021-03-25 18:40 UTC, oleitao commented
> @oleitao Do you really think we should include the option to compare with other Files? I think the properties dialog should be limited to the selected file. Also, can you put the hashes section after the details section?

@yaichenbaum i saw that suggestion on [3722](https://github.com/files-community/Files/issues/3722) but i can remove that. Please let me know.

2021-03-25 18:54 UTC, yaichenbaum commented
@oleitao It's up to you, but in my opinion, if it's working fine, we might as well keep it.

2021-03-25 19:22 UTC, oleitao commented
> @oleitao It's up to you, but in my opinion, if it's working fine, we might as well keep it.

I've a some suggestions about an previous related PR [4121](https://github.com/files-community/Files/pull/4121) which is related with MD5 hash generation. 

- In order to don't have MD5 hash on two placed Properties -> General(tab) and Properties -> Hashes (tab). I suggest to remove MD5 hash field of General tab.

- Discard that PR [4121](https://github.com/files-community/Files/pull/4121) 

Do you agree?

2021-03-25 20:33 UTC, yaichenbaum commented
> Do you agree?
@oleitao I agree, it should only be in one place.

2021-03-26 00:08 UTC, yaichenbaum commented
@oleitao Should the compare option be a little lower down on the page similar to the screenshot shared in the issue you linked?

2021-03-26 12:33 UTC, oleitao commented
> @oleitao Should the compare option be a little lower down on the page similar to the screenshot shared in the issue you linked?

@yaichenbaum i removed the compare option. Do you want to add compare option again?

2021-03-26 13:53 UTC, yaichenbaum commented
> > @oleitao Should the compare option be a little lower down on the page similar to the screenshot shared in the issue you linked?
> 
> @yaichenbaum i removed the compare option. Do you want to add compare option again?

It's good either.

2021-04-02 18:47 UTC, tsvietOK requested changes
Resolve conflicts, please.

2021-04-02 18:47 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml.cs
> +        private async void btnCompareHash_Click(object sender, RoutedEventArgs e)
Method names should start with uppercase letter.

2021-04-02 18:47 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml.cs
> +                            txtCompareHash.Text = await (BaseProperties as FileProperties).GetSystemFileHashes(HashAlgorithmNames.Md5, file);
Instead of changing text directly, create property and bind it to txtCompareHash in XAML.

2021-04-02 18:47 UTC, tsvietOK commented on Files/Interacts/Interaction.cs
> +    public class Crc32
Can you move this class to separate file, please?

2021-04-02 18:47 UTC, tsvietOK commented on Files/Interacts/Interaction.cs
>              {
Interaction.cs file is deprecated.

2021-04-06 21:09 UTC, tsvietOK requested changes
Did you test your changes? Nothing happens when opening Hashes tab (except CRC32 hash)
![image](https://user-images.githubusercontent.com/20501502/113778668-5f212280-9735-11eb-86a8-bf657baa983e.png)
By the way, CRC32 hash should be 04CE0987.

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/Properties.xaml
> +                        <FontIcon FontFamily="{StaticResource FluentGlyphs}" Glyph="&#xE946;" />
Looks like there is no such FontFamily.

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml.cs
> +        private void ddlCompareHash_SelectionChanged(object sender, SelectionChangedEventArgs e)
Method names should start with uppercase letter.

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml
> +                x:Name="itemMD5HashValue"
Control name should start with uppercase letter.

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml
> +            <ComboBox x:Name="ddlCompareHash"
What does `ddl` means?

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml
> +                x:Name="btnCompareHash"
Meaningful name.

2021-04-06 21:09 UTC, tsvietOK commented on Files/Views/Pages/PropertiesHashes.xaml
> +                x:Name="txtCompareHash"
Meaningful name.

2021-04-06 22:21 UTC, oleitao commented on Files/Views/Pages/PropertiesHashes.xaml
> +            <ComboBox x:Name="ddlCompareHash"
DropDownList

2021-04-07 18:48 UTC, oleitao commented
> By the way, CRC32 hash should be 04CE0987.

I've tested CRC32 and compared the output with [Hash Viewer](https://www.microsoft.com/en-us/p/hash-viewer-md5-crc32-sha1-sha256-sha384-sha512/9ngzvxxzwhrq?cid=msft_web_chart&activetab=pivot:overviewtab) and all CRC32 generated hashes was mathed.

![Capture1](https://user-images.githubusercontent.com/72361786/113918266-1d968300-97da-11eb-9f40-afe183c14836.PNG)

![Capture2](https://user-images.githubusercontent.com/72361786/113918281-22f3cd80-97da-11eb-88bf-f752550a4ef8.PNG)

![Capture3](https://user-images.githubusercontent.com/72361786/113918299-27b88180-97da-11eb-94b7-798e5c00b5ed.PNG)

2021-04-10 19:43 UTC, tsvietOK commented on Files/Views/Pages/Properties.xaml
> +                        <FontIcon FontFamily="{StaticResource FluentGlyphs}" Glyph="&#xE946;" />
Still not fixed.

2021-04-10 20:10 UTC, tsvietOK requested changes
1. The calculating progresses of SHA1 and CRC32 hashes are not displayed.
2. Wrong CRC32 hash.
![image](https://user-images.githubusercontent.com/20501502/114282952-c8fc3d80-9a4f-11eb-85d2-c611e991b664.png)
![image](https://user-images.githubusercontent.com/20501502/114282954-cd285b00-9a4f-11eb-9ea3-aa7437646dbf.png)
3. The SHA1 hash is truncated.
4. Sometimes it is blocking UI thread.
5. How to compare Text hash wit calculated hash?
6. Sometimes when canceling calculation crc32 hash app crashes.
Please, test it properly before submitting for review.

2021-04-18 02:18 UTC, yaichenbaum commented
@oleitao Can you address the requested changes?

2021-04-18 18:16 UTC, oleitao commented
> @oleitao Can you address the requested changes?

@yaichenbaum yes i can. Tomorrow i will start to work on requested changes.

2021-04-21 18:38 UTC, oleitao commented
> @oleitao Can you address the requested changes?

It's better not address this PR to me.

2021-04-27 15:43 UTC, closed without merging