Update translation: PT-BR
files-community/Files pull request #4416
Opened 2021-04-01 21:53 UTC by LuanRoger

**Details of Changes**
- Updated PT-BR language

**Validation**
- [x] Built and ran the app.

2021-04-02 18:25 UTC, tsvietOK requested changes
Looks like you modified `Resources.resw` file manually. All changes should be done only in `Files.pt-BR.xlf`. In PR include only .xlf file. For more details see our [documentation](https://files-community.github.io/docs/#/articles/translating-files).

2021-04-03 11:36 UTC, LuanRoger commented
@tsvietOK I didn't modify the file manually, but I think I know why it is as modified:
I created an issue (#4402) explaining that the language was not changing from PT-PT to PT-BR, but it is really changing the language but some strings are the same, which was not meant to be.
When I did the merge of the upstream for my fork I chose not to bring these two files because I had already worked with them, so the only thing that should have been modified would be Files.pt-BR.xlf, but as I explained earlier this does not happen.

2021-04-04 18:55 UTC, tsvietOK commented
I recommend you to exclude Resources file from this PR, since it will be regenerated later.

2021-04-04 18:55 UTC, tsvietOK commented
I guess the problem is here. (target-language)
https://github.com/files-community/Files/blob/cd2f0355bf8bfabe18c31647ca49a0d5cff79763/Files/MultilingualResources/Files.pt-PT.xlf#L3

2021-04-04 19:12 UTC, tsvietOK commented on Files/MultilingualResources/Files.pt-BR.xlf
> +          <source>App Language</source>
By the way, don't change string in `source` tag, the value is taken from Strings/en-US/Resources.resw file. Just change translation in `target` tag.

2021-04-06 21:25 UTC, tsvietOK approved these changes

2021-04-06 21:43 UTC, merged