Remember sidebar items state #4128
files-community/Files pull request #4585
Opened 2021-04-13 19:25 UTC by oleitao

**Resolved / Related Issues**
Itemize resolved / related issues by this PR.
- Remember sidebar sections state

**Details of Changes**
Add details of changes here.
- Added into settings preferences an option to allow to enable remember last sections sidebar states

**Validation**
How did you test these changes?
- [x] Change section sidebar states
- [x] Close Files
- [x] Open Files and check if sections states are the same as previous

2021-04-13 19:34 UTC, yaichenbaum commented
> Added into settings preferences an option to allow to enable remember last sections sidebar states

@oleitao This shouldn't be a setting, this should be the default behavior.

2021-04-13 21:47 UTC, oleitao commented
> > Added into settings preferences an option to allow to enable remember last sections sidebar states
> 
> @oleitao This shouldn't be a setting, this should be the default behavior.

@yaichenbaum i change remember last sections sidebar states to work as default behaviour.

2021-04-13 23:15 UTC, winston-de commented
It only seems to remember the state for the drives and cloud drive sections.

https://user-images.githubusercontent.com/59544401/114632347-64212d00-9c73-11eb-9d2d-d4cb86dc28bb.mp4

2021-04-13 23:17 UTC, winston-de commented
Also, is it supposed to remember the state after collapsing the sidebar?

https://user-images.githubusercontent.com/59544401/114632496-a9ddf580-9c73-11eb-9c30-2f444e6019cb.mp4

2021-04-14 13:03 UTC, oleitao commented
> Also, is it supposed to remember the state after collapsing the sidebar?
> 
>  2021-04-13-161606_Trim.mp4

@winston-de that's strange...
I did the follow changes on section then closed Files and open again and checked the section was open or closed based on my last action:

- Favorites (open)
- Library (close)
- Drives (open)
- CloudDrives (close)
- Network (open)

----------------------

- Favorites (close)
- Library (open)
- Drives (close)
- CloudDrives (open)
- Network (close)

----------------------

- Favorites (close)
- Library (close)
- Drives (close)
- CloudDrives (close)
- Network (close)

----------------------

- Favorites (open)
- Library (open)
- Drives (open)
- CloudDrives (open)
- Network (open)

----------------------

changes before close Files
![Capture1](https://user-images.githubusercontent.com/72361786/114714275-dce2c080-9d29-11eb-8972-10c12991e396.PNG)

open again Files
![Capture2](https://user-images.githubusercontent.com/72361786/114714297-e3713800-9d29-11eb-8346-f3dcd3113eaf.PNG)

2021-04-14 16:57 UTC, oleitao commented
> Also, is it supposed to remember the state after collapsing the sidebar?
> 
>  2021-04-13-161606_Trim.mp4

That's strange, as you can see that works fine to me:

![test1](https://user-images.githubusercontent.com/72361786/114749421-d7e23900-9d4a-11eb-80ff-a361c61c9319.gif)

![test2](https://user-images.githubusercontent.com/72361786/114749446-dd3f8380-9d4a-11eb-9ddc-a29df75e7d86.gif)

2021-04-15 06:23 UTC, winston-de commented
Interesting, the first issue seems to be solved after resetting the dev app. However, it still doesn't remember the state after collapsing the sidebar. Do you have any idea why that may be?

2021-04-15 06:25 UTC, winston-de requested changes

2021-04-15 06:25 UTC, winston-de commented on Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs
> +        private bool rememberSidebarState = App.AppSettings.ShowLibrarySection;
Since there isn't an option anymore, could you please remove this?

2021-04-15 13:33 UTC, yaichenbaum commented
@oleitao The state of sidebar items was already being saved, the issue is that collapsing and then expanding the sidebar again would reset the state.

2021-04-21 22:42 UTC, closed without merging