Multiple Files Properties: Move Files And Folders Count next to the i…
files-community/Files pull request #4647
Opened 2021-04-16 22:26 UTC by oleitao

…con #1225

**Resolved / Related Issues**
Itemize resolved / related issues by this PR.
- Move files and folders Count next to the icon on Properties panel

![Capture1](https://user-images.githubusercontent.com/72361786/115089680-afa13880-9f0a-11eb-8196-6273b4e4d31b.PNG)

![Capture2](https://user-images.githubusercontent.com/72361786/115089685-b4fe8300-9f0a-11eb-985d-96638faded0a.PNG)

2021-04-18 03:07 UTC, winston-de requested changes
Why are you using a TextBox for this? It makes much more sense to use a TextBlock for this.
![image](https://user-images.githubusercontent.com/59544401/115132778-09137100-9fb8-11eb-8daf-d467e0c894f1.png)

2021-04-18 18:31 UTC, winston-de commented
When a single folder is selected, it shows it's contents label instead of it's name. 
![image](https://user-images.githubusercontent.com/59544401/115156524-7ca99280-a039-11eb-8c26-f6c4e07f24a1.png)

2021-04-18 18:33 UTC, winston-de commented
Also, you may want to use a separate control for this then the item name TextBox, as you have now inadvertently removed the ability to rename items from the properties dialog.

2021-04-18 18:37 UTC, yaichenbaum commented
The issue in question is no longer relevant since it was opened before we displayed the item name.

2021-04-19 18:17 UTC, oleitao commented
@yaichenbaum you closed and reopen that issue. I don't know if is to continue the development or that topic is no more required?

2021-04-19 18:18 UTC, yaichenbaum commented
@oleitao Let's continue development on this.

2021-04-19 21:55 UTC, oleitao commented
![test1](https://user-images.githubusercontent.com/72361786/115308185-3dc32c00-a162-11eb-8165-5b70ce408ae9.gif)

2021-04-20 16:09 UTC, winston-de commented
Looking good, just a few things.

Could you put the name text box back into it's previous position (centered). Like this:
![image](https://user-images.githubusercontent.com/59544401/115427945-c23f9a00-a1b6-11eb-9c23-4b8f9b8efd23.png)

Also, could you please center this label as well?
![image](https://user-images.githubusercontent.com/59544401/115428695-80632380-a1b7-11eb-8eb3-b8ca035f2de1.png)

Lastly, the name text box seems to be missing from the shortcut tab. Could you please add it back?
![image](https://user-images.githubusercontent.com/59544401/115429207-0bdcb480-a1b8-11eb-90e4-8dec9d040cf0.png)

2021-04-25 07:16 UTC, winston-de commented
I'm getting a crash when opening the dialog, it looks like you are trying to use a TextBox style on a TextBlock.

```
2021-04-25 00:13:37.5082|ERROR|Files.App|Exception has been thrown by the target of an invocation.|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.TextBox' to an object of type 'Windows.UI.Xaml.Controls.TextBlock'. [Line: 91 Position: 17]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Files.Views.PropertiesGeneral.InitializeComponent()
   at Files.Views.PropertiesGeneral..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at Files.Views.Properties.NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
   at Windows.UI.Xaml.Controls.NavigationView.put_SelectedItem(Object value)
   at Files.Views.Properties.XamlBindingSetters.Set_Windows_UI_Xaml_Controls_NavigationView_SelectedItem(NavigationView obj, Object value, String targetNullValue)
   at Files.Views.Properties.Properties_obj1_Bindings.Update_TabGeneral(NavigationViewItem obj, Int32 phase)
   at Files.Views.Properties.Properties_obj1_Bindings.Update_(Properties obj, Int32 phase)
   at Files.Views.Properties.Properties_obj1_Bindings.Update()
   at Files.Views.Properties.Properties_obj1_Bindings.Initialize()
   at Files.Views.Properties.Properties_obj1_Bindings.Loading(FrameworkElement src, Object data)
```

2021-04-27 21:50 UTC, oleitao commented
> I'm getting a crash when opening the dialog, it looks like you are trying to use a TextBox style on a TextBlock.
> 
> ```
> 2021-04-25 00:13:37.5082|ERROR|Files.App|Exception has been thrown by the target of an invocation.|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.
> 
> Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.TextBox' to an object of type 'Windows.UI.Xaml.Controls.TextBlock'. [Line: 91 Position: 17]
>    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
>    at Files.Views.PropertiesGeneral.InitializeComponent()
>    at Files.Views.PropertiesGeneral..ctor()
>    --- End of inner exception stack trace ---
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
>    at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
>    at Files.Views.Properties.NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
>    at Windows.UI.Xaml.Controls.NavigationView.put_SelectedItem(Object value)
>    at Files.Views.Properties.XamlBindingSetters.Set_Windows_UI_Xaml_Controls_NavigationView_SelectedItem(NavigationView obj, Object value, String targetNullValue)
>    at Files.Views.Properties.Properties_obj1_Bindings.Update_TabGeneral(NavigationViewItem obj, Int32 phase)
>    at Files.Views.Properties.Properties_obj1_Bindings.Update_(Properties obj, Int32 phase)
>    at Files.Views.Properties.Properties_obj1_Bindings.Update()
>    at Files.Views.Properties.Properties_obj1_Bindings.Initialize()
>    at Files.Views.Properties.Properties_obj1_Bindings.Loading(FrameworkElement src, Object data)
> ```

@winston-de  I already tried to replicate that error, but everything works fine. Can you describe what you did to get that error?

2021-04-27 22:34 UTC, winston-de commented
@oleitao It may not always cause a crash, but there definitely are mismatched types in the styles.

2021-04-27 22:37 UTC, winston-de requested changes

2021-04-27 22:37 UTC, winston-de commented on Files/Views/Pages/PropertiesGeneral.xaml
> +                Style="{StaticResource PropertyValueTextBox}"
```suggestion
                Style="{StaticResource PropertyValueTextBlock}"
```

```PropertyValueTextBox``` is a ```TextBox``` style, please switch to ```PropertyValueTextBlock```

2021-05-19 01:26 UTC, winston-de requested changes
Can you please fix the following issues and resolve the merge conflicts?
- Count is shown when viewing properties of single folder
![image](https://user-images.githubusercontent.com/59544401/118742712-cc7ca480-b805-11eb-8a3e-ad4e2b5537e8.png)

- Item name is missing for shortcuts
![image](https://user-images.githubusercontent.com/59544401/118742934-35fcb300-b806-11eb-9f85-b0805175ba78.png)

2021-06-09 00:21 UTC, yaichenbaum commented
Closing this PR due to inactivity.

2021-06-09 00:21 UTC, closed without merging