Add shortcut keys for layouts
files-community/Files pull request #4809
Opened 2021-05-01 06:14 UTC by cinqmilleans

Add keyboard shortcuts for layouts: ctrl+shift+1/6.
Reorder layouts in menu, from the smallest to the biggest.

2021-05-12 19:39 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +    <value>Details View (Ctrl+Shift+2)</value>
Isn't the shortcut automatically displayed in the tooltip?

2021-05-12 19:41 UTC, yaichenbaum requested changes

2021-05-12 19:41 UTC, yaichenbaum commented on Files/Helpers/ContextFlyoutItemHelper.cs
> +                            KeyboardAccelerator = new KeyboardAccelerator{Key = VirtualKey.Number1, Modifiers = VirtualKeyModifiers.Control | VirtualKeyModifiers.Shift}
```suggestion
                            KeyboardAccelerator = new KeyboardAccelerator{Key = VirtualKey.Number1, Modifiers = VirtualKeyModifiers.Control | VirtualKeyModifiers.Shift, IsEnabled=False}
```

Can you make this change to the rest of them as well?

2021-05-12 19:41 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        CornerRadius="4"
```suggestion
```

2021-05-13 13:55 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +    <value>Details View (Ctrl+Shift+2)</value>
@cinqmilleans

2021-05-13 15:22 UTC, cinqmilleans commented
@yaichenbaum This PR has become too complicated because it covers portions of code that have changed a lot. I propose to reapply the changes from the current state. I need to know what to do with the tooltips (see my post above).

2021-05-13 15:34 UTC, yaichenbaum commented
@cinqmilleans My question above was if it's necessary to add the shortcuts to the tooltip since they should be added automatically regardless.

2021-05-19 03:34 UTC, yaichenbaum submitted a review, later dismissed

2021-05-19 03:34 UTC, yaichenbaum commented
@cinqmilleans Can you resolve the merge conflicts?

2021-05-19 05:46 UTC, winston-de submitted a review, later dismissed

2021-05-19 05:52 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Details View (Ctrl+Shift+2)">
```suggestion
                                        ToolTipService.ToolTip="Details View (Ctrl+Shift+1)">
```

2021-05-19 05:53 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Tiles View (Ctrl+Shift+3)">
```suggestion
                                        ToolTipService.ToolTip="Tiles View (Ctrl+Shift+2)">
```

2021-05-19 05:53 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Grid View (Small) (Ctrl+Shift+4)">
```suggestion
                                        ToolTipService.ToolTip="Grid View (Small) (Ctrl+Shift+3)">
```

2021-05-19 05:53 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Grid View (Medium) (Ctrl+Shift+5)">
```suggestion
                                        ToolTipService.ToolTip="Grid View (Medium) (Ctrl+Shift+4)">
```

2021-05-19 05:53 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Grid View (Large) (Ctrl+Shift+6)">
```suggestion
                                        ToolTipService.ToolTip="Grid View (Large) (Ctrl+Shift+5)">
```

2021-05-19 05:53 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
> +                                        ToolTipService.ToolTip="Column View (Ctrl+Shift+1)">
```suggestion
                                        ToolTipService.ToolTip="Column View (Ctrl+Shift+6)">
```

2021-05-19 15:56 UTC, cinqmilleans commented
@yaichenbaum This pr changes the order of the layouts from smallest to largest (column / detail / tile / grid small-> medium-> large), in the context menu and in the navigationtoolbar (which does not currently display the same order) . This is the order that is used for the shortcuts. So I did not apply your changes.

2021-05-19 16:23 UTC, yaichenbaum commented
> @yaichenbaum This pr changes the order of the layouts from smallest to largest (column / detail / tile / grid small-> medium-> large), in the context menu and in the navigationtoolbar (which does not currently display the same order) . This is the order that is used for the shortcuts. So I did not apply your changes.

As discussed in the issue, we would prefer to keep the current order since it's arranged by what's used more often.

2021-05-19 16:34 UTC, cinqmilleans commented
@yaichenbaum Ok for me. The changes you proposed only modify the tooltips. I'll edit to keep the current order.

2021-05-19 16:40 UTC, yaichenbaum commented
> @yaichenbaum Ok for me. The changes you proposed only modify the tooltips. I'll edit to keep the current order.

Correct, that was just the general idea 🙂

2021-05-20 13:00 UTC, cinqmilleans commented
@yaichenbaum It is done.

2021-05-20 14:56 UTC, yaichenbaum submitted a review, later dismissed

2021-05-21 04:52 UTC, winston-de commented
Looks good, but can you please resolve the merge conflicts?

2021-05-21 15:36 UTC, cinqmilleans commented
@winston-de You are right. The merge is resolved.

2021-05-21 15:44 UTC, winston-de approved these changes
LGTM, nice work!

2021-05-21 16:04 UTC, merged