Improves tab menu
files-community/Files pull request #4839
Opened 2021-05-05 12:56 UTC by cinqmilleans

**Resolved / Related Issues**
Improves tab menu in horizontal mode. #4796

**Details of Changes**
Add command to reopen last closed.
show shortcuts in the menu.

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
![tabmenu](https://i.ibb.co/9wCnY2Q/tabmenu.png)

2021-05-05 13:10 UTC, yaichenbaum requested changes

2021-05-05 13:10 UTC, yaichenbaum commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                                <KeyboardAccelerator Key="T" Modifiers="Control" />
```suggestion
                                <KeyboardAccelerator Key="T" Modifiers="Control" IsEnabled="False"  />
```

2021-05-05 13:10 UTC, yaichenbaum commented on Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
> +                                <KeyboardAccelerator Key="T" Modifiers="Control,Shift" />
```suggestion
                                <KeyboardAccelerator Key="T" Modifiers="Control,Shift" IsEnabled="False" />
```

2021-05-05 13:23 UTC, cinqmilleans commented
@yaichenbaum You are right.

2021-05-05 13:34 UTC, yaichenbaum approved these changes

2021-05-12 19:48 UTC, yaichenbaum approved these changes
LGTM

2021-05-12 19:50 UTC, merged