Fix async methods
files-community/Files pull request #4863
Opened 2021-05-08 14:33 UTC by cinqmilleans

**Resolved / Related Issues**
Some async methods don't use await.
Some sync methods could be async for better performance.
This causes compiler warnings. 

**Details of Changes**
Modify async/sync state if necessary.
Disable warning if necessary (implementation of an interface)

2021-05-23 17:40 UTC, gave92 requested changes

2021-05-23 17:40 UTC, gave92 commented on Files/Filesystem/Cloud/Providers/AmazonDriveProvider.cs
> +    #pragma warning restore 1998
This should be one line up (on line 38)

2021-05-24 08:08 UTC, cinqmilleans commented
@gave92 You are right. It is fixed.

2021-05-24 08:14 UTC, gave92 submitted a review, later dismissed

2021-05-24 13:08 UTC, yaichenbaum commented
@cinqmilleans Can you solve the merge conflicts?

2021-05-24 14:31 UTC, yaichenbaum approved these changes

2021-05-24 14:31 UTC, merged