Ctrlf
files-community/Files pull request #4942
Opened 2021-05-17 20:59 UTC by gave92

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- For #2247

**Details of Changes**
Add details of changes here.
Code taken from #3558
- Adds "Ctrl + F" keyboard shortcut to open the searchbox and "Esc" to close it

**Validation**
How did you test these changes?
- [x] Built and ran the app

2021-05-18 07:29 UTC, Jaiganeshkumaran commented
Does it focus on the last focused element after you press esc? There was this bug in the original PR which I couldn't fix.

2021-05-18 20:26 UTC, gave92 commented
> Does it focus on the last focused element after you press esc? There was this bug in the original PR which I couldn't fix.

Code is the taken straight from #3558, has the same issue ;)

2021-05-19 02:00 UTC, yaichenbaum requested changes

2021-05-19 02:00 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +    <value>Search (Ctrl + F)</value>
```suggestion
    <value>Search (Ctrl+F)</value>
```

2021-05-19 02:00 UTC, yaichenbaum commented on Files/UserControls/NavigationToolbar.xaml
>                  ToolTipService.ToolTip="Search">
```suggestion
                ToolTipService.ToolTip="Search (Ctrl+F)">
```

2021-05-19 14:31 UTC, yaichenbaum approved these changes

2021-05-19 14:31 UTC, merged