Update translation: pt-BR
files-community/Files pull request #5381
Opened 2021-07-07 11:35 UTC by LuanRoger

**Resolved / Related Issues**
- Strings not translated in PT-BR.

**Validation**
- [x] Built and ran the app.

2021-07-08 16:49 UTC, gave92 requested changes

2021-07-08 16:49 UTC, gave92 commented on Files/MultilingualResources/Files.pt-BR.xlf
> +          <target state="needs-review-translation">Insira a sobreposição compacta</target>
Is this translation updated? If so you can set `state="translated"`

2021-07-08 16:49 UTC, gave92 commented on Files/MultilingualResources/Files.pt-BR.xlf
> +          <target state="needs-review-translation">Remova a sobreposição compacta</target>
Is this translation updated? If so you can set `state="translated"`

2021-07-09 06:35 UTC, gave92 submitted a review, later dismissed

2021-07-11 02:44 UTC, yaichenbaum commented
@LuanRoger Can you resolve the merge conflicts?

2021-07-11 13:16 UTC, gave92 approved these changes

2021-07-11 14:44 UTC, merged