Update Files.hu-HU.xlf
files-community/Files pull request #5572
Opened 2021-07-27 10:56 UTC by KristofKekesi

This PR is still in progress, please don't merge it yet.

2021-07-28 07:18 UTC, nvi9 requested changes

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Keresés</target>
```suggestion
          <target state="translated">Kiválasztás</target>
```
Other alternatives: `Választás`, `Mappaválasztás`

This is a text of the button for opening folder picker dialog:

![image](https://user-images.githubusercontent.com/42123156/127279536-d6d47e68-cf6e-442c-b4e9-70fdc96a1c91.png)

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Tömörítettlen méret</target>
```suggestion
          <target state="translated">Tömörítetlen méret</target>
```

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Levétel a kedvencek közűl</target>
```suggestion
          <target state="translated">Levétel a kedvencek közül</target>
```

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Levétel a kedvencek közűl</target>
```suggestion
          <target state="translated">Levétel a kedvencek közül</target>
```

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Frissítések elérhetőek</target>
```suggestion
          <target state="translated">Frissítések elérhetők</target>
```

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Frissítések elérhetőek a telepítésre</target>
```suggestion
          <target state="translated">Frissítések érhetők el telepítésre</target>
```

2021-07-28 07:18 UTC, nvi9 commented on Files/MultilingualResources/Files.hu-HU.xlf
> +          <target state="translated">Adatok hozzáadása</target>
```suggestion
          <target state="translated">Hozzáfűzés</target>
```

2021-07-28 08:57 UTC, KristofKekesi commented
Thanks @nvi9

2021-08-02 20:35 UTC, gave92 approved these changes

2021-08-02 21:27 UTC, merged

2021-08-02 22:07 UTC, gave92 commented
Sigh I've missed an issue in this resource file, project does not compile