Open zip archives and empty folders in ColumnView
files-community/Files pull request #5914
Opened 2021-08-23 22:13 UTC by gave92

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #5878, #5908
- Closes #5905

**Details of Changes**
Add details of changes here.
- Open zip archives and empty folders in ColumnView
- Add API contract check for ShouldConstrainToRootBounds flyout property 

**Validation**
How did you test these changes?
- [x] Built and ran the app

2021-08-23 23:55 UTC, yaichenbaum approved these changes

2021-08-24 01:02 UTC, winston-de reviewed
should some indication be shown when a folder is empty?

2021-08-24 01:58 UTC, yaichenbaum commented
> should some indication be shown when a folder is empty?
> this snipped should work
> `<uc:FolderEmptyIndicator Grid.Row="3" Margin="0,125,0,0" HorizontalAlignment="Center" VerticalAlignment="Top" Canvas.ZIndex="0" EmptyTextType="{x:Bind ParentShellPageInstance.FilesystemViewModel.EmptyTextType, Mode=OneWay}" />`

That's a good idea but what's the purpose of the margin?

2021-08-24 02:01 UTC, winston-de commented
the margin keeps it from being directly at the top of the page

2021-08-24 02:26 UTC, yaichenbaum commented
> the margin keeps it from being directly at the top of the page (may not be needed)

Shouldn't it be centered vertically?

2021-08-24 05:27 UTC, gave92 commented
⁉️

2021-08-24 05:33 UTC, yaichenbaum commented
> ⁉️

@gave92 what's the question mark on 😆

2021-08-24 05:34 UTC, gave92 commented
> should some indication be shown when a folder is empty?
this snipped should work

Lol, confused about this discussion and how it's related to this PR

2021-08-24 18:19 UTC, winston-de commented
> > should some indication be shown when a folder is empty?
> this snipped should work
> 
> Lol, confused about this discussion and how it's related to this PR and if it's a request to change something.
> 
> Edit: aaah you mean that no text is shown for an empty folder in column view?

Yeah thats what i meant, sorry for not being clear lol

2021-08-24 18:21 UTC, winston-de submitted a review, later dismissed

2021-08-24 18:43 UTC, yaichenbaum requested changes

2021-08-24 18:43 UTC, yaichenbaum commented on Files/Views/LayoutModes/ColumnViewBase.xaml
> +            Margin="0,125,0,0"
```suggestion
```

2021-08-24 18:43 UTC, yaichenbaum commented on Files/Views/LayoutModes/ColumnViewBase.xaml
> +            VerticalAlignment="Top"
```suggestion
            VerticalAlignment="Center"
```

2021-08-24 19:54 UTC, yaichenbaum approved these changes
Great work!

2021-08-24 20:46 UTC, merged