Added context menu options to rearrange Favorites item
files-community/Files pull request #5979
Opened 2021-08-30 13:51 UTC by BanCrash

Opening this as a draft since there is still a visual bug that I didn't figure out how to fix it.

I will try to solve this, but since the timeline for the V2 is almost done I suggest to set a timeline also for this, and if I can't solve this issue since it's only visual merge this and open a new issue to fix it in the future.

The issue is that when you move the actual selected item, it will stay as selected even if you select another one:

![image](https://user-images.githubusercontent.com/11770760/131349487-527e9550-00a4-4903-848d-d13bb1d0e84b.png)

**Resolved / Related Issues**
- Related #1069

**Details of Changes**
- Added context menu options to rearrange Favorites item (right click on an item to have to option to move it up/down/top/bottom).

**Current limitations**
- Not available for Home nor Recycle bin. Maybe in a future PR.
- There is a bug when you move the actual selected item, that it will keep it selected even if you switch to another selected item until you select it back again.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/11770760/131349567-45cc6799-354c-4c33-b27d-52e48e9d5d50.png)

2021-08-30 19:14 UTC, BanCrash commented
I think the bug I've found it's not from Files but from WinUi. I've found this similar issue, though not exactly the same: 
https://github.com/microsoft/microsoft-ui-xaml/issues/2845

And also this that I'm not sure neither if it's the same: https://github.com/microsoft/microsoft-ui-xaml/issues/3015

2021-08-30 20:07 UTC, yaichenbaum commented on Files/Strings/en-US/Resources.resw
> +  </data>
```suggestion
  <data name="SideBarFavoritesMoveOneDown" xml:space="preserve">
    <value>Move one down</value>
  </data>
  <data name="SideBarFavoritesMoveOneUp" xml:space="preserve">
    <value>Move one up</value>
  </data>
  <data name="SideBarFavoritesMoveToBottom" xml:space="preserve">
    <value>Move to bottom</value>
  </data>
  <data name="SideBarFavoritesMoveToTop" xml:space="preserve">
    <value>Move to top</value>
  </data>
```

2021-08-30 20:07 UTC, yaichenbaum requested changes

2021-08-30 20:07 UTC, yaichenbaum commented on Files/UserControls/SidebarControl.xaml.cs
> +                    ShowItem = ShowMoveItemDown
```suggestion
                    Text = "SideBarFavoritesMoveToTop".GetLocalized(),
                    Glyph = "\uE11C",
                    Command = new RelayCommand(() => MoveItemToTop_Click(null, null)),
                    ShowItem = ShowMoveItemUp
                },
                new ContextMenuFlyoutItemViewModel()
                {
                    Text = "SideBarFavoritesMoveOneUp".GetLocalized(),
                    Glyph = "\uE70E",
                    Command = new RelayCommand(() => MoveItemUp_Click(null, null)),
                    ShowItem = ShowMoveItemUp
                },
                new ContextMenuFlyoutItemViewModel()
                {
                    Text = "SideBarFavoritesMoveOneDown".GetLocalized(),
                    Glyph = "\uE70D",
                    Command = new RelayCommand(() => MoveItemDown_Click(null, null)),
                    ShowItem = ShowMoveItemDown
                },
                new ContextMenuFlyoutItemViewModel()
                {
                    Text = "SideBarFavoritesMoveToBottom".GetLocalized(),
                    Glyph = "\uE118",
                    Command = new RelayCommand(() => MoveItemToBottom_Click(null, null)),
                    ShowItem = ShowMoveItemDown
```

2021-08-30 20:49 UTC, R3voA3 commented
While I like the idea of being able to change the order of appearance, wouldn't it be more intuitive to just be able to drag and drop the items?

2021-08-30 20:53 UTC, BanCrash commented
> While I like the idea of being able to change the order of appearance, wouldn't it be more intuitive to just be able to drag and drop the items? With the context menu, rearranging many items can become tedious.

My idea would be to have both ways and everyone choose whatever option they want (or even sometimes one and sometimes the other). But currently there is a but on WinUI that doesn't allow to have the drag and drop functionality. When that bug is fixed we can have also that way.

2021-08-30 20:55 UTC, R3voA3 commented
> > While I like the idea of being able to change the order of appearance, wouldn't it be more intuitive to just be able to drag and drop the items? With the context menu, rearranging many items can become tedious.
> 
> My idea would be to have both ways and everyone choose whatever option they want (or even sometimes one and sometimes the other). But currently there is a bug on WinUI that doesn't allow to have the drag and drop functionality. When that bug is fixed we can have also that way.

Sounds great!

2021-08-30 22:50 UTC, yaichenbaum commented
> While I like the idea of being able to change the order of appearance, wouldn't it be more intuitive to just be able to drag and drop the items? With the context menu, rearranging many items can become tedious.

As @BanCrash mentioned, drag and drop would be ideal, but until the WinUI issue is resolved, we're implementing this as a workaround.

2021-08-31 16:56 UTC, gave92 approved these changes
Nice!

2021-08-31 17:07 UTC, yaichenbaum approved these changes

2021-08-31 17:07 UTC, merged