Update zh-Hant
files-community/Files pull request #6083
Opened 2021-09-08 12:02 UTC by open3

**Details of Changes**
- Updated Chinese Traditional translations

**Validation**
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

2021-09-09 19:35 UTC, BanCrash commented on Files/MultilingualResources/Files.zh-Hant.xlf
> +          <note from="MultilingualEditor" annotates="source" priority="4"></note>
Is this note intentional?

2021-09-09 19:38 UTC, BanCrash commented on Files/MultilingualResources/Files.zh-Hant.xlf
> +</target>
```suggestion
  </target>
```

Just a little change for keeping indentation consistency.

2021-09-09 19:47 UTC, BanCrash requested changes
It's almost completed, just let me know if that comment is intentional and fix the little indentation issue and this will be approved ;)

2021-09-10 12:42 UTC, open3 commented
All the issues have been resolved 👍

2021-09-11 00:45 UTC, BanCrash approved these changes

2021-09-12 04:23 UTC, merged

2021-09-12 04:23 UTC, yaichenbaum commented
@open3 thank you!