[Proof of concept] - Set Files as Open dialog
files-community/Files pull request #6107
Opened 2021-09-12 12:08 UTC by gave92

**Description**
A funny experiment to see if it's possible to replace the shell file open dialog with Files (spoiler: it's possible!)
This is by no means complete, work is necessary on the Files side to adapt the interface for the purpose but it shows what is possible to achieve.

**How to install**
- Uninstall the Store/Release version of Files if you have it
- Deploy this PR as normal
- Run the `Installer.exe` found in `Files\Files.OpenDialog\Installer\bin\Debug`

**How to use**
- Trigger the open dialog and enjoy you're favorite Files manager open
- Select a file
- Close the app

**How to restore default dialog**
- Run the Installer from the command line with the "/u" option (`> Installer.exe /u`)

**Notes**
- Does not work for older apps that use a different way to show the files open dialog (e.g Notepad)
- The Installer adds a couple of registry keys in HKEY_CURRENT_USER, I don't think it has the capability to blowing up your PC but keep in mind the warnings about registry edits ;)

**Validation**
How did you test these changes?
- [x] Built and ran the app

2021-09-12 19:43 UTC, yaichenbaum commented
@gave92 which apps does this work with?

2021-09-12 19:45 UTC, gave92 commented
@yaichenbaum at least notepad++, Microsoft edge, visual studio.

2021-09-12 19:46 UTC, gave92 commented
> @gave92 which apps does this work with?

Added tested apps to the top post.

2021-09-12 19:49 UTC, yaichenbaum commented
@gave92 looks like a good start! How do you envision users setting this up?

2021-09-12 19:50 UTC, gave92 commented
> @gave92 looks like a good start! How do you envision users setting this up?

We can probably offer an option in Files settings to set/unset Files as default explorer and as open file dialog.

2021-09-13 12:50 UTC, sylveon commented
The way this is currently implemented, it results in the .NET Framework Runtime being loaded in every process that opens a file browse dialog. While it's not a shell extension directly, the same [concerns that MS raises against writing C# shell extensions](https://docs.microsoft.com/en-us/windows/win32/shell/shell-and-managed-code) applies. This will lead to a higher likelyhood of crashes/bugs, and puts the burden of these issues on third party application devs (faulty shell extensions is already why many apps implement their own file browser instead of using the system one).

I would ***strongly*** recommend rewriting this portion in C++, as it seems to be mostly trivial anyways (and it would allow you to use the correct way to register COM classes, `regsvr32`, instead of registry files).

2021-09-13 20:04 UTC, gave92 commented
Yeah a rewrite in C++ is coming. But I suck at C++ and I wanted to see if this thing was working before getting my hands dirty ;)

>  allow you to use the correct way to register COM classes, regsvr32

I'd still use the reg file: regsvr32 install the dll in HKEY_LOCAL_MACHINE. I prefer the current that writes stuff to HKCU instead (less risky and you don't need to be administrator).

2021-09-13 22:01 UTC, sylveon commented
regsvr32 just calls `DllRegisterServer`. The DLL can do whatever it wants in that, including registering in HKCU. The default does use HKLM, but you can change it.

2021-09-13 22:55 UTC, gave92 commented
> regsvr32 just calls `DllRegisterServer`. The DLL can do whatever it wants in that, including registering in HKCU. The default does use HKLM, but you can change it.

That's good, thanks!

2021-09-14 05:44 UTC, sumeshir26 commented
Would this work with the 'Save As' Dialog?

2021-09-14 21:38 UTC, d2dyno1 commented
> Would this work with the 'Save As' Dialog?

I found no instances of `IFileSaveDialog` so I presume the answer is no

2021-09-15 07:18 UTC, gave92 commented
> Would this work with the 'Save As' Dialog?

Can be done for Save Dialog too, but currently not implemented

2021-09-15 07:18 UTC, gave92 commented
Converting to draft till the porting to C++ is done.

2021-09-17 17:24 UTC, gave92 commented
Converted dll to C++ 💪. Curious if someone had the guts to test this xD

2021-09-17 18:09 UTC, sylveon commented
looks okay to me. The files use italian comments but that's because of VS.

Can also get rid of the two reg files and call `regsvr32.exe /n /i:user thing.dll` (add `/u` to uninstall)

2021-09-18 13:03 UTC, gave92 commented
Added ability to set Files as default file manager and optionally as file open dialog from Files Experimental settings.
The option to use Files as open file dialog should be hidden before merging the PR as it's really early stage.

2021-09-20 01:41 UTC, winston-de commented
Just tested it, works great in apps like Edge. It seems to be causing uwp apps like your phone or quick pad to crash or just not do anything when attempting to invoke the file picker.

2021-09-20 07:14 UTC, gave92 commented
@winston-de for UWP apps it fails miserably with an InvalidCastExpeption. The custom dialog constructor gets called but that's it, no clue, sigh,

2021-09-20 13:16 UTC, sylveon commented
Check the calls to QueryInterface, you're probably missing an interface.

2021-09-20 19:21 UTC, gave92 commented
Thanks @sylveon it looks like I'm missing the following:
```
QueryInterface: {FC4801A3-2BA9-11CF-A229-00AA003D7352} = IObjectWithSite
QueryInterface: {79EAC9EE-BAF9-11CE-8C82-00AA004BA90B} = IInternetSecurityManager
```

2021-09-21 00:01 UTC, gave92 commented
@winston-de thanks to @sylveon pointers and @Cthulhu intervention it looks like UWP apps now work correctly, could you confirm?

2021-09-21 04:23 UTC, winston-de commented
Works now :)

One other issue, if you try and open more then one dialog at a time (click open in two different apps), this error will be shown (if you click ignore it crashes).
![image](https://user-images.githubusercontent.com/59544401/134111061-029e13bc-7e3b-4c2a-a595-ac72713a942c.png)

2021-09-21 07:23 UTC, gave92 commented
@winston-de thanks should be just because of the debug logs to the same file. Disabled logging now & hidden the "Set as open file dialog" UI option.

2021-09-21 12:05 UTC, winston-de submitted a review, later dismissed
lgtm

2021-09-23 02:00 UTC, yaichenbaum requested changes

2021-09-23 02:00 UTC, yaichenbaum commented on Files/Views/SettingsPages/Experimental.xaml
> +                x:Uid="SettingsSetAsOpenDialog"
I've been working on moving over to a new method of supporting translations via `x:Bind`, do you think you can use this method as well? https://devblogs.microsoft.com/ifdef-windows/use-a-custom-resource-markup-extension-to-succeed-at-ui-string-globalization/

2021-09-26 01:46 UTC, yaichenbaum commented
@gave92 is the option to set Files as the open file dialog supposed to be hidden?

2021-09-26 06:35 UTC, gave92 commented
Yeah I would enable it once some work has been done to adapt Files UI for the purpose.

2021-09-26 17:27 UTC, yaichenbaum commented
> Yeah I would enable it once some work has been done to adapt Files UI for the purpose.

Should double clicking a file be disabled when Files is acting as the open file dialog?

2021-09-26 17:38 UTC, gave92 commented
@yaichenbaum many thing should change when Files is used as open file dialog (no tabs? an ok button? support for file types filters?), this is "just" ground work.

2021-09-30 13:01 UTC, winston-de commented
Can you resolve the merge conflicts please?

2021-09-30 13:15 UTC, winston-de commented
Also side note, maybe we should add a link to app execution alias settings, in case the files.exe execution alias has been disabled (which would break the default explorer setting).

2021-09-30 14:19 UTC, yaichenbaum commented
> Also side note, maybe we should add a link to app execution alias settings, in case the files.exe execution alias has been disabled (which would break the default explorer setting).

Once the user toggles this switch, should we adjust the execution alias in the event is was disabled?

2021-10-01 06:25 UTC, gave92 commented
Merged main.

2021-10-01 12:07 UTC, winston-de approved these changes

2021-10-01 13:43 UTC, yaichenbaum approved these changes
Great work! LGTM

2021-10-01 13:44 UTC, merged

2021-10-18 02:29 UTC, neoOpus commented
Yes Please! this would be the best option so far and from there make it more robust, also, please integrate some of Listary features for the Open/Save Dialog... also make it easy to switch to Windows Explorer just in case something isn't working properly in some scenarios (on fly without the need to change the default explorer)

2021-11-04 10:07 UTC, vivadavid commented
Hi, I've enabled "Set files as default explorer", but now I can't disable it. I've tried uninstalling the app, but then I can't even use the Windows file explorer.

I'm on version Versión: 2.0.33.0, OS Version: 10.0.19043.1288.

I'd appreciate some help! Thanks!

2021-11-04 10:19 UTC, BanCrash commented
@vivadavid Hi, follow the steps here to unset it: https://files.community/docs/configuring/replace-file-explorer

You need to use the UnsetFilesAsDefault.reg file.

2021-11-04 11:02 UTC, vivadavid commented
Thank you, @BanCrash ! I tried to do it manually, but I must have done something wrong. However running the reg file did the trick and things are back to normal.