Update Files.el.xlf
files-community/Files pull request #6789
Opened 2021-11-07 22:14 UTC by spyrag

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

2021-11-08 15:55 UTC, yaichenbaum requested changes

2021-11-08 15:55 UTC, yaichenbaum commented on Files/MultilingualResources/Files.el.xlf
> +          <target state="new">Στήλη ημερομηνίας δημιουργίας</target>
```suggestion
          <target state="translated">Στήλη ημερομηνίας δημιουργίας</target>
```
Can you update the state for the rest of the strings as well?

2021-11-09 02:40 UTC, yaichenbaum approved these changes
Thank you!

2021-11-09 03:46 UTC, yaichenbaum commented
@spyrag can you look into why this isn't working to compile in VS?

2021-11-09 20:50 UTC, vodafone999 approved these changes
Done

2021-11-22 16:17 UTC, yaichenbaum commented
@spyrag were you able to fix the build issue?

2021-11-28 15:14 UTC, closed without merging