Specified target OS
files-community/Files pull request #6819
Opened 2021-11-08 23:32 UTC by Gitoffthelawn

**Resolved / Related Issues**
Items resolved / related issues by this PR.
N/A

**Details of Changes**
Add details of changes here.
Specifies target OS.
**Validation**

How did you test these changes?
N/A

**Screenshots (optional)**
N/A

2021-11-08 23:43 UTC, yaichenbaum requested changes

2021-11-08 23:43 UTC, yaichenbaum commented on README.md
> +Files is a Windows file manager with a powerful yet intuitive design. It has features like multiple tabs, panes, columns, shell extensions in the context menu and tags.
```suggestion
Files is a file manager for Windows with a powerful yet intuitive design. It has features like multiple tabs, panes, columns, shell extensions in the context menu and tags.
```

2021-11-09 00:20 UTC, duke7553 approved these changes
LGTM

2021-11-09 01:26 UTC, yaichenbaum approved these changes

2021-11-09 01:26 UTC, merged