Update Files.zh-Hans.xlf
files-community/Files pull request #6842
Opened 2021-11-10 14:26 UTC by SudaCat

translate new strings

2021-11-10 16:02 UTC, yaichenbaum requested changes

2021-11-10 16:02 UTC, yaichenbaum commented on Files/MultilingualResources/Files.zh-Hans.xlf
> +</target>
```suggestion
          <target state="translated">兼容性</target>
```

2021-11-11 04:08 UTC, SudaCat commented
accepted the suggestion, and done.

2021-11-14 07:21 UTC, yaichenbaum approved these changes

2021-11-14 07:21 UTC, merged