Issue 7032
files-community/Files pull request #7078
Opened 2021-11-25 20:56 UTC by gave92

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #7032

**Details of Changes**
Add details of changes here.
- Extends the import/export command in About page to all settings. Settings are exported in a .zip file. It includes: pinned items, user settings, file tags, terminal profiles, bundles. On import, all settings are applied without restart.

**Validation**
How did you test these changes?
- [x] Built and ran the app

2021-11-25 20:56 UTC, gave92 commented
@yaichenbaum this is the proposal discussed in #7032

2021-11-25 21:07 UTC, yaichenbaum approved these changes, later dismissed

2021-11-26 00:25 UTC, gave92 commented
Uops pushed to the wrong branch, restored

2021-11-26 15:10 UTC, yaichenbaum approved these changes, later dismissed

2021-11-26 18:38 UTC, d2dyno1 requested changes

2021-11-26 18:38 UTC, d2dyno1 commented on Files/Filesystem/StorageItems/ZipStorageFile.cs
> +        private IAsyncOperation<ZipFile> OpenZipFileAsync(bool readWrite, bool openProtected = false)
Can you pass in `FileAccessMode`?

2021-11-26 18:38 UTC, d2dyno1 commented on Files/Filesystem/StorageItems/ZipStorageFile.cs
> +                        return new FileStream(hFile, FileAccess.Read).AsRandomAccessStream();
Can this follow `accessMode` parameter?

2021-11-26 18:48 UTC, gave92 commented on Common/FileTagsDb.cs
> +            var dataValues = JsonSerializer.DeserializeArray(json);
Yeah but we have a catch in AboutViewModel. In any case I'll make this method coherent with the other ImportSettings methods.

2021-11-26 18:49 UTC, gave92 commented on Files/Controllers/SidebarPinnedController.cs
> +            StorageFolder Folder = await FilesystemTasks.Wrap(() => ApplicationData.Current.LocalFolder.CreateFolderAsync("settings", CreationCollisionOption.OpenIfExists).AsTask());
No need, FilesystemResult is useful only if we care about why the call has failed. Here we really don't.

2021-11-26 18:50 UTC, gave92 commented on Files/Controllers/SidebarPinnedController.cs
> +        private async Task<IEnumerable<string>> ReadV1PinnedItemsFile()
@yaichembaum should we drop support for old "PinnedItems.txt"? Don't quite remember how old is that.

2021-11-26 23:52 UTC, gave92 commented on Common/FileTagsDb.cs
> +            var dataValues = JsonSerializer.DeserializeArray(json);
Actually most other ImportSettings() methods (e.g. UserSettings) don't do exception handling, keeping like this for now. The catch in AboutViewModel is enough.

2021-11-26 23:54 UTC, gave92 commented on Files/Controllers/SidebarPinnedController.cs
> +        private async Task<IEnumerable<string>> ReadV1PinnedItemsFile()
Not removed, but given priority to V2 which is what 99% of users will have.

2021-11-28 14:14 UTC, d2dyno1 approved these changes

2021-11-28 15:12 UTC, yaichenbaum approved these changes

2021-11-28 15:12 UTC, yaichenbaum commented
@gave92 thank you!

2021-11-28 15:12 UTC, merged