Fix mistranslations in `Files.ja-JP.xlf`.
files-community/Files pull request #7649
Opened 2022-01-14 15:25 UTC by h1g0

**Resolved / Related Issues**
Items resolved / related issues by this PR.

**Details of Changes**
Add details of changes here.

- Corrected some text that had already been translated into Japanese, but where mistranslations or typos existed.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

2022-01-14 15:30 UTC, yaichenbaum commented
@h1g0 before we merge this, can you add your agreement to #7625?

2022-01-14 15:42 UTC, h1g0 commented
@yaichenbaum 
>before we merge this, can you add your agreement to #7625?

I commented my agreement [here](https://github.com/files-community/Files/issues/7625#issuecomment-1013233428).
Thank you for the notice!

2022-01-14 15:44 UTC, yaichenbaum requested changes

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">このフォルダとファイル</target>
```suggestion
          <target state="translated">このフォルダとファイル</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">このフォルダ、サブフォルダおよびファイル</target>
```suggestion
          <target state="translated">このフォルダ、サブフォルダおよびファイル</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">ペインを閉じる</target>
```suggestion
          <target state="translated">ペインを閉じる</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">元のフォルダ</target>
```suggestion
          <target state="translated">元のフォルダ</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">アイテムの追加</target>
```suggestion
          <target state="translated">アイテムの追加</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">フォルダの追加</target>
```suggestion
          <target state="translated">フォルダの追加</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">お気に入りに固定</target>
```suggestion
          <target state="translated">お気に入りに固定</target>
```

2022-01-14 15:44 UTC, yaichenbaum commented on src/Files/MultilingualResources/Files.ja-JP.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">すべてのファイルとフォルダを表示</target>
```suggestion
          <target state="translated">すべてのファイルとフォルダを表示</target>
```

2022-01-14 15:46 UTC, yaichenbaum approved these changes
LGTM

2022-01-14 16:12 UTC, merged

2022-01-15 00:57 UTC, onein528 commented
@h1g0 Im a Japanese. do you think of wide-chars(such as "！" or "？")?
I think  it will be replaced with narrow(or half width)-chars like "!" or "?". And according to a previous contribution about my Japanese localization resource(#6141), I followed the following rules:

**Translation rules**

* `!` to `！`
* `?` to `？`
* Insert a half-width space between katakana words. (For example, `Drives Widget` translated to `ドライブ ウィジェット` )
* Insert a half-width space between English and Japanese ( For example `View Files privacy policy` translated to `Files のプライバシーポリシーを見る`).
---
**Issue translations**
* [here](https://github.com/files-community/Files/blob/main/src/Files/MultilingualResources/Files.ja-JP.xlf#L111)
* [here](https://github.com/files-community/Files/blob/main/src/Files/MultilingualResources/Files.ja-JP.xlf#L131)
* [here](https://github.com/files-community/Files/blob/main/src/Files/MultilingualResources/Files.ja-JP.xlf#L559)
---

**Below, GitHub is usually recommended to write in English, but I will write it in Japanese(avoiding misunderstand).**
* 複数行ある場合のみ「。」を使うべき。もしくは元のリソースで「.」が語尾にある場合のみ。
* 僕の考えとしては、かっこが「()」と半角が使われるのであれば、「?」も「!」も半角であるべきだ。
* 見にくさを防ぐため上記のルールに従う半角英数字のため、英数字と日本語との間に半角スペースが必要。

What do you think based on the above? If you agree this, I will open a PR about this.

2022-01-15 08:35 UTC, h1g0 commented
@onein528 
I also think, in principle, wide characters should be used for letters (i.e. `！`, `？`, `（`, `）`, etc.) in the translation.
Exceptionally, only half-width characters should be used at the end of half-width characters such as English words.

In addition, what about the long vowel symbol `ー` at the end of words ( e.g. `フォルダー` or `フォルダ` )?
The translation for `folder` was mixed between `フォルダー` and `フォルダ`, so I have standardized it to `フォルダ` in this PR.
However, I think that this also needs to be discussed and unified rules established.

So I have the following thoughts on your translation rules (I also write in Japanese):

>複数行ある場合のみ「。」を使うべき。もしくは元のリソースで「.」が語尾にある場合のみ。

- 原則として、文末の句読点等は原文に従うのが望ましいと考えます。

>僕の考えとしては、かっこが「()」と半角が使われるのであれば、「?」も「!」も半角であるべきだ。でもほかの終端文字が「。」と大文字なのに対して、「!」や「?」を使うと見にくい可能性がある。

- 原則として、日本語の訳文に対しては記号も全角「！」「？」「（」「）」を使用すべきだと考えています。ただし、その記号が英単語等の半角文字に対して使用される場合は、半角とすべきだと思います。

>見にくさを防ぐため上記のルールに従う半角英数字のため、英数字と日本語との間に半角スペースが必要。

- こちらは賛成です。英数字と日本語との間、および英単語をカタカナ表記した場合の単語間にも半角スペースを挿入することが望ましいと思います（例： `ドライブ ウィジェット`）。

- 単語末の長音記号の省略の是非（例：`フォルダー` と `フォルダ` ）について
  - 原則的には、初めてその単語を訳出する訳者が一般的だと思えば省略可としたいです。
  - 例えば「フォルダー」よりも「フォルダ」の表記のほうが個人的には違和感がないのですが、これは人によると思います。　
  - いずれにしても、アプリケーション全体でどちらかに統一されているべきだと思います。
  - なので、既出の単語は他の箇所に従って訳出し、初出の単語はとりあえず訳者のセンスで訳出した後でPRに対するコメントという形で議論すれば良いかな、と考えています。

2022-01-15 08:52 UTC, onein528 commented
Yes, I agree all of this.

> I think that this also needs to be discussed and unified rules established.

I think too.

@yaichenbaum I think we should create translation practices file. Do you think of this?