Update Polish language
files-community/Files pull request #8057
Opened 2022-01-31 07:44 UTC by Daxxxis

**Details of Changes**
- Updated Polish language

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [x] Tested the changes for accessibility

2022-01-31 09:02 UTC, d2dyno1 requested changes

2022-01-31 09:02 UTC, d2dyno1 commented on src/Files/MultilingualResources/Files.pl-PL.xlf
> +          <target state="translated">Nie usuwaj aplikacji Files ze swojego urządzenia bez wyłączania tej opcji. Nie zrobienie tego uniemożliwi ci otwarcie Eksploratora plików.</target>
```suggestion
          <target state="translated">Nie usuwaj aplikacji Files ze swojego urządzenia bez wyłączania tej opcji. Nie zrobienie tego uniemożliwi Ci otwarcie Eksploratora Plików.</target>
```

2022-01-31 09:02 UTC, d2dyno1 commented on src/Files/MultilingualResources/Files.pl-PL.xlf
> +          <target state="needs-review-translation">Wsperaj nas na GitHubie</target>
```suggestion
          <target state="translated">Wsperaj nas poprzez GitHub</target>
```

2022-01-31 09:25 UTC, Daxxxis commented on src/Files/MultilingualResources/Files.pl-PL.xlf
> +          <target state="translated">Nie usuwaj aplikacji Files ze swojego urządzenia bez wyłączania tej opcji. Nie zrobienie tego uniemożliwi ci otwarcie Eksploratora plików.</target>
![image](https://user-images.githubusercontent.com/60961958/151768670-9fe8055e-9f27-4932-a522-290e7f4f4f1f.png)

2022-02-01 23:57 UTC, d2dyno1 approved these changes

2022-02-01 23:58 UTC, merged