Update lang id-ID
files-community/Files pull request #8164
Opened 2022-02-05 09:21 UTC by shiazza

- Added some words 
- And changed a few typo

2022-02-05 10:14 UTC, shiazza commented
Changed a few mistakes and added another language to make it easier to understand

2022-02-05 12:31 UTC, d2dyno1 commented
Can you add your agreement to #7625?

2022-02-05 13:57 UTC, shiazza commented
> Bisakah Anda menambahkan perjanjian Anda ke #7625?



> Can you add your agreement to #7625?

I can

2022-02-05 14:31 UTC, d2dyno1 requested changes

2022-02-05 14:31 UTC, d2dyno1 commented on src/Files/MultilingualResources/Files.id-ID.xlf
> +          <target state="new">Lisensi Pihak ke tiga</target>
Please change the `state="new"` to `state="translated"` and in other places too!

2022-02-05 14:31 UTC, d2dyno1 commented on src/Files/MultilingualResources/Files.id-ID.xlf
> +          <target state="translated" state-qualifier="tm-suggestion">Berkas</target>
Could you remove `state-qualifier="tm-suggestion"` and in other places too

2022-02-06 08:34 UTC, shiazza commented
>[d2dyno1] Reply

Done All completed

2022-02-06 09:43 UTC, d2dyno1 approved these changes

2022-02-06 09:43 UTC, merged