Sidebar context menu for sections visibility
files-community/Files pull request #8317
Opened 2022-02-12 15:25 UTC by aleksanderlukasiewicz

**Resolved / Related Issues**
- Closes #8233 

**Details of Changes**
- Added context menu to sidebar
- Added 3 new localizations in en-US

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/69370471/153717271-24117e5f-9d0b-4c72-99a2-acfa0905eada.png)

2022-02-12 18:06 UTC, gave92 commented
Nice, I suppose with this the "Sidebar" section in settings could be removed. @yaichenbaum?

2022-02-12 18:43 UTC, aleksanderlukasiewicz commented
> Nice, with this the "Sidebar" section in settings could potentially be removed. @yaichenbaum?

If the sections were removed from the settings it would make it easier to centralize the sidebar settings. Now, the sidebar options are split into several view models (AppearanceViewModel, SidebarViewModel and other), which is why the code is written in C# and not in XAML with the proper data bindings.

2022-02-13 00:15 UTC, yaichenbaum commented
> Nice, with this the "Sidebar" section in settings could potentially be removed. @yaichenbaum?

@gave92 there is still a benifit of having the settings available in the dialog.

2022-02-13 00:15 UTC, yaichenbaum commented
@aleksanderlukasiewicz is there a scenario where someone will want to hide all the sections?

2022-02-13 02:28 UTC, yaichenbaum requested changes

2022-02-13 07:19 UTC, gave92 commented
> @aleksanderlukasiewicz is there a scenario where someone will want to hide all the sections?

If removing all sections would make the sidebar completely disappear that yes

2022-02-13 07:28 UTC, yaichenbaum commented
@gave92 that's not currently part of the spec

2022-02-13 10:35 UTC, aleksanderlukasiewicz commented on src/Files/UserControls/SidebarControl.xaml.cs
> +            var sidebarContextMenu = new MenuFlyout();
Sure

2022-02-13 13:30 UTC, aleksanderlukasiewicz commented on src/Files/UserControls/SidebarControl.xaml.cs
> +            var sidebarContextMenu = new MenuFlyout();
Done!

2022-02-13 13:31 UTC, aleksanderlukasiewicz commented
> @aleksanderlukasiewicz is there a scenario where someone will want to hide all the sections?

Yea there is an option for this.

2022-02-13 15:57 UTC, yaichenbaum commented
@aleksanderlukasiewicz my question was if the option is necessary, can you remove it?

2022-02-13 16:26 UTC, oleklukasiewicz commented
@yair100  Okay sure!

2022-02-13 16:34 UTC, aleksanderlukasiewicz commented
@yaichenbaum  Something like this?
![image](https://user-images.githubusercontent.com/69370471/153762972-15226333-b9db-47ba-be8a-ee8ff4a6bfcc.png)

2022-02-13 16:38 UTC, yaichenbaum commented
@aleksanderlukasiewicz yes

2022-02-13 17:45 UTC, aleksanderlukasiewicz commented
@yaichenbaum Done!

2022-02-13 18:11 UTC, yaichenbaum commented
@aleksanderlukasiewicz hiding the network section and then showing it again appears to collapse the other sections.

2022-02-13 18:15 UTC, aleksanderlukasiewicz commented
@yaichenbaum ok I'll look into it

2022-02-13 19:16 UTC, oleklukasiewicz commented
@yair100 This looks like a much deeper problem related to more than just the network section. I noticed similar behavior when I changed section visibility from the settings page.

2022-02-13 19:49 UTC, yaichenbaum commented
> @yaichenbaum This looks like a much deeper problem related to more than just the network section. I noticed similar behavior when I changed section visibility from the settings page.

For some reason it only appears to happen from the context menu on my end 🤔

2022-02-13 21:20 UTC, aleksanderlukasiewicz commented
> > @yaichenbaum This looks like a much deeper problem related to more than just the network section. I noticed similar behavior when I changed section visibility from the settings page.
> 
> For some reason it only appears to happen from the context menu on my end 🤔

Strange, I get this error even in version 2.1.7.0 without the context menu. 🤔
I think it's a problem (at least from what I have) with the sidebar control itself.

2022-02-20 18:47 UTC, gave92 approved these changes

2022-02-20 19:13 UTC, yaichenbaum approved these changes

2022-02-20 19:13 UTC, merged