Add "newFile" option
files-community/Files pull request #850
Opened 2020-05-26 11:57 UTC by lampenlampen

Adds a "newFile" option to the various "new"-menus (see #719).

![files_newDialog](https://user-images.githubusercontent.com/26199386/82897217-90e32d80-9f57-11ea-89bd-1cae0413ff23.png)

If you click the "file"-option the normal rename dialog opens.

![files_renameDialog](https://user-images.githubusercontent.com/26199386/82897247-9fc9e000-9f57-11ea-953a-b4fc751d7b3f.png)

and there you can specify the file with file extension (e.g. `test.md`).

To-Do
1. I added two new strings `x:Uid="ModernNavigationToolbaNewFile"` and `x:Uid="BaseLayoutContextFlyoutNewFile"` in xaml, but i don't know, if i have to add them to the `resources.resw` or ...
2. I didn't changed the `renameDialog`, so it still shows the "Rename file without file extension". I wasn't sure, if it's better to create a new dialog for creating files or to alter the existing one.

2020-05-26 12:48 UTC, yaichenbaum commented
@lampenlampen I am not sure if we want to continue work on the dialog, I think it makes more sense to improve this feature by moving it over the the right click context menu. Please let us know your thoughts.

2020-05-26 12:56 UTC, lampenlampen commented
It is added to all "create item"-menus (the right click menu and the one in the toolbar). I only posted a screenshot of the dialog.

The dialog is nice because it can be invoked and navigated by keyboard.

2020-05-26 12:57 UTC, yaichenbaum commented
@lampenlampen That is a good point, perhaps the dialog should show when you use the keyboard shortcut, but we should also add the options to the right click context menu.

2020-05-26 12:59 UTC, lampenlampen commented
Do you mean this?

![files_rightClickMenu](https://user-images.githubusercontent.com/26199386/82903612-7c0b9780-9f61-11ea-957b-303210525a99.png)

2020-05-26 13:04 UTC, lampenlampen commented
The dialog is already shown when you press `Strg+Shift+n`.

2020-05-26 13:18 UTC, yaichenbaum commented
> Do you mean this?
> 
> ![files_rightClickMenu](https://user-images.githubusercontent.com/26199386/82903612-7c0b9780-9f61-11ea-957b-303210525a99.png)

Yes, that is what I was referring to. It would also be great if instead of the dialog, it had an inline textbox to type the name.

2020-05-26 13:39 UTC, tsvietOK commented
I think it is better to create new folder by pressing ctrl+shift+n shortcut (like in explorer)(and users create folders more often), instead of displaying create item dialog
What about this PR, how often you create an empty file without extension?

2020-05-26 14:25 UTC, lampenlampen commented
@yaichenbaum I'm not sure about which dialog you are speaking. The "rename" or the "newItem" one.
@tsvietOK I didn't change any shortcuts. That was preconfigured. As long we have a shortcut for opening the "newItem" dialog, we can change it.

2020-05-26 19:09 UTC, tsvietOK requested changes
On your first [screenshot](https://user-images.githubusercontent.com/26199386/82897217-90e32d80-9f57-11ea-89bd-1cae0413ff23.png) there is File description "Create a file with file extension", but on the next [screenshot](https://user-images.githubusercontent.com/26199386/82897247-9fc9e000-9f57-11ea-953a-b4fc751d7b3f.png) textbox placeholder text "Enter an item name without an extension". So, we should somehow fix this inconsistency

2020-05-26 19:11 UTC, yaichenbaum commented
I think that instead of showing a dialog to choose a name, it should have an inline editor like file rename has.

2020-05-26 19:56 UTC, lampenlampen commented on Files/Dialogs/AddItemDialog.xaml.cs
> +            switch ((e.ClickedItem as AddListItem).Type)
Should be resolved after 3 commits now 😃.

2020-05-26 22:26 UTC, duke7553 commented
One more nitpick: You should probably use the E7C3 icon glyph to represent a generic item.

2020-07-18 09:28 UTC, Jaiganeshkumaran commented
@yaichenbaum Please merge this PR soon so that I can start working on #1368.

2020-07-19 02:14 UTC, yaichenbaum commented
> @yaichenbaum Please merge this PR soon so that I can start working on #1368.

As soon as merge conflicts are solved, and the code passes review, the pull request will be merged.

2020-08-02 03:14 UTC, seltinusjulio commented
I think it make sense also if we have "Duplicate" option in context menu, instead copy-paste.

2020-08-02 03:18 UTC, Jaiganeshkumaran commented
@seltinusjulio We should also have "Move" option similar to the File Explorer ribbon.

2020-08-25 23:23 UTC, yaichenbaum commented
@lampenlampen Do you mind solving the merge conflicts so we can merge this in?

2020-09-03 14:45 UTC, closed without merging