feat(details-view): add option to size all columns to fit
files-community/Files pull request #9090
Opened 2022-05-04 20:29 UTC by jiejasonliu

**Resolved / Related Issues**
- Closes #8384
- Fix regression of #5506

**Details of Changes**
- Add `Size All Columns to Fit` to details menu flyout in detail view header
- Make `ResizeColumnToFit` safe to call programmatically, previously only safe to call when user clicks on visible column
- Improve heuristic to calculate appropriate width since measuring `TextBlock` is expensive
   - Measure longest text _first_ because we can expect that the width should be long enough for shorter texts regardless if they have wider letters or not; 
   - This also allows the width to not overshoot, imagine if the first files were wide letters: 
   **(e.g. AAA, BBB, DDD)** --> this would skew the average letter width
- Fix regression of "double click `GridSplitter` (divider)" in header to resize column
  - Caused by a change where the majority of `TextBlock` were no longer being nested in `Grid` 
  (#7824)

**Validation**
- [X] Built and ran the app
- [X] Tested the changes for accessibility

**Screenshots (optional)**

- feature (size all columns to fit):
![Files-8384-menu-item](https://user-images.githubusercontent.com/29434693/166820153-ad28e704-48a5-402f-b241-a0c62f21763e.gif)

---

- regression fix (resize on double click divider):
![Files-8384-regress-dbclick](https://user-images.githubusercontent.com/29434693/166820247-27d9d841-cc2e-4a9d-821c-e121676b9a93.gif)

2022-05-04 21:30 UTC, gave92 commented on src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
> +                3 => FileList.Items.Cast<ListedItem>().Select(x => (x as RecycleBinItem)?.ItemOriginalPath?.Length ?? 0).Max(), // original path column
Is this change just "stylistic"?

2022-05-06 19:14 UTC, gave92 submitted a review, later dismissed

2022-05-08 14:17 UTC, yaichenbaum requested changes

2022-05-08 14:17 UTC, yaichenbaum approved these changes

2022-05-12 14:14 UTC, merged

2022-05-12 14:14 UTC, yaichenbaum commented
@jiejasonliu thank you!