[Post 2.3] Add support for alternate streams
files-community/Files pull request #9234
Opened 2022-05-22 12:54 UTC by gave92

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #177

**Details of Changes**
Add details of changes here.
- Add basic support for alternate streams
- Alternate data streams appear as semitransparent files under the main file (main file: "file_name" -> ADS: "file_name:ads_name")
- Copy/move/delete/rename operations work (but filelist must be manually refreshed)
- Opening ADS will copy it to temporary folder first (otherwise it can't be opened by external programs)
- Preview pane works

**Validation**
How did you test these changes?
- [x] Built and ran the app

**Screenshots (optional)**
Add screenshots here.
![image](https://user-images.githubusercontent.com/9673091/169696085-91e80be5-4549-4578-899d-ca8b61fd2d5c.png)

2022-05-31 06:56 UTC, hez2010 commented
I think we should provide an option to hide files-specified ADS which is used for color tag.

2022-06-09 19:36 UTC, gave92 commented
Not sure if it'd be worth it to have that setting as alternate data streams is already a very niche functionality for power users. I'd trust them to not delete ADS unless they know what they're doing. \+ @yaichenbaum for opinions.

2022-06-09 19:40 UTC, yaichenbaum commented
I'm not very familiar with this topic so I don't have an opinion but we can make changes as necessary down the line.

2022-06-16 01:51 UTC, yaichenbaum commented
@hez2010 are you familiar enough with ADS to review this PR?

2022-06-16 02:55 UTC, hez2010 commented
> are you familiar enough with ADS to review this PR?

I have some experience with ADS though might not that sufficient, but feel free to assign me for CR :)

2022-06-16 03:45 UTC, yaichenbaum commented
> > are you familiar enough with ADS to review this PR?
> 
> I have some experience with ADS though might not that sufficient, but feel free to assign me for CR :)

It doesn't look like can assign you since you're not in the org but you can still add a review (I can add you if you're intrested in joining).

2022-06-16 03:58 UTC, hez2010 commented
> I can add you if you're intrested in joining

Yes, definitely interested in!

2022-06-17 19:50 UTC, gave92 commented on src/Files.Uwp/Filesystem/ListedItem.cs
> +                var nameWithoutExtension = Path.GetFileNameWithoutExtension(ItemNameRaw);
mm probably not worth it, the file list already evaluates the ItemName property only when the ItemNameRaw changes (and that you'd have to do even if name is cached).

2022-06-20 05:30 UTC, hez2010 requested changes
Nice additions to functionality!

While I do not totally agree with the current implementation strategy of the display of ADS. 

I would prefer implementing ADS display in the context menu:

![image](https://user-images.githubusercontent.com/14960345/174531539-25f97ea1-08e1-4f81-9bab-82f03a90f718.png)

In this way we can resolve at least 3 issues:

1. We don't need to update the ADS on filesystem update (which is also not supported by filesystem)
2. We can distinguish the `View` operation from `Open` operation, because we are actually open a copy of the data stream and any changes to the copy won't reflect on the original ADS
3. We don't need to enumerate ADSs while populating the list from a given path, instead we postpone it to the time users focusing on the ADS context menu, so the performance willbe better.

2022-06-21 18:44 UTC, gave92 commented on src/Files.Uwp/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
> +                else if (moveResult.Items.All(x => x.HResult == -1)) // ADS
I agree that moving an ADS in not a common operation but I like treating them like normal files.. and you could always copy an ADS and then delete it :) I'm not hung on this, but support for move comes for free.

2022-06-21 18:46 UTC, gave92 commented on src/Files.FullTrust/MessageHandlers/ApplicationLaunchHandler.cs
> +                            var isAlternateStream = Regex.IsMatch(application, @"\w:\w");
Here it's ok because it's the last method we're going to try (WSL files should have already been handled)). I'm gonna check in the other places.

2022-06-21 22:37 UTC, gave92 commented on src/Files.FullTrust/MessageHandlers/ApplicationLaunchHandler.cs
> +                            var isAlternateStream = Regex.IsMatch(application, @"\w:\w");
Ok does not seem to be a problem. When reading files from WSL containing a colon ":" the returned file name has the colon replaced with a weird character. Same happens in explorer. A colon should guarantee that it's an ADS.

2022-06-22 06:28 UTC, hez2010 approved these changes
Nice work. LTGM.

2022-06-22 12:56 UTC, merged